import { commitSearchParams } from '@/lib/search-params';
import { List, Map } from 'lucide-react';
import { useCallback, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router';
import { Button, EmptyState, ErrorState, PageHeader } from '@/components/ui';
import type { DataTableQueryState } from '@/components/ui/data-table';
import { FeedingPointFilterBar } from '../components/feeding-point-filter-bar';
import { FeedingPointSummaryCards } from '../components/feeding-point-summary';
import { FeedingPointsMapView } from '../components/feeding-points-map-view';
import { FeedingPointsTable } from '../components/feeding-points-table';
import { useFeedingPoints, useFeedingPointSummary } from '../hooks';
import { feedingPointCreatorTypes, feedingPointStatuses, type FeedingPointFilters } from '../types';
import { hasFeedingPointFilters } from '../utils';
const valid=<T extends string>(value:string|null,options:readonly T[]):T|undefined=>value&&options.includes(value as T)?value as T:undefined;
function fromParams(params:URLSearchParams):FeedingPointFilters{return{search:params.get('q')??'',status:valid(params.get('status'),feedingPointStatuses),creatorType:valid(params.get('creatorType'),feedingPointCreatorTypes),governorate:params.get('governorate')??undefined,pendingRefills:params.has('pendingRefills')?params.get('pendingRefills')==='true':undefined,organizationId:params.get('organizationId')??undefined,hasOpenIssues:params.has('hasOpenIssues')?params.get('hasOpenIssues')==='true':undefined,updatedFrom:params.get('updatedFrom')??undefined,updatedTo:params.get('updatedTo')??undefined,page:Math.max(1,Number(params.get('page')??1)||1),pageSize:[10,20,50].includes(Number(params.get('pageSize')))?Number(params.get('pageSize')):10,sortBy:(params.get('sortBy') as FeedingPointFilters['sortBy'])??'updatedAt',sortDirection:params.get('sortDirection')==='asc'?'asc':'desc'};}
function toParams(filters:FeedingPointFilters){const params=new URLSearchParams();const entries:Array<[string,string|number|boolean|undefined]>=[['q',filters.search||undefined],['status',filters.status],['creatorType',filters.creatorType],['governorate',filters.governorate],['pendingRefills',filters.pendingRefills],['organizationId',filters.organizationId],['hasOpenIssues',filters.hasOpenIssues],['updatedFrom',filters.updatedFrom],['updatedTo',filters.updatedTo],['page',filters.page>1?filters.page:undefined],['pageSize',filters.pageSize!==10?filters.pageSize:undefined],['sortBy',filters.sortBy&&filters.sortBy!=='updatedAt'?filters.sortBy:undefined],['sortDirection',filters.sortDirection==='asc'?'asc':undefined]];for(const[key,value]of entries)if(value!==undefined)params.set(key,String(value));return params;}
export function FeedingPointsPage(){const[params,setParams]=useSearchParams();const filters=useMemo(()=>fromParams(params),[params]);const[view,setView]=useState<'LIST'|'MAP'>('LIST');const query=useFeedingPoints(filters),summary=useFeedingPointSummary();const update=useCallback((patch:Partial<FeedingPointFilters>)=>commitSearchParams(params,toParams({...filters,...patch}),setParams),[filters,params,setParams]);const clear=()=>setParams(new URLSearchParams());const active=hasFeedingPointFilters(filters);const governorates=useMemo(()=>Array.from(new Set((query.data?.items??[]).map(point=>point.location.governorate))).sort((a,b)=>a.localeCompare(b,'ar')),[query.data?.items]);const onState=useCallback((state:DataTableQueryState)=>{const sort=state.sorting[0];update({page:state.pageIndex+1,pageSize:state.pageSize,sortBy:(sort?.id as FeedingPointFilters['sortBy'])??filters.sortBy,sortDirection:sort?.desc?'desc':'asc'});},[filters.sortBy,update]);const emptyTitle=filters.status==='PENDING'?'لا توجد طلبات نقاط جديدة بانتظار المراجعة.':filters.pendingRefills?'لا توجد تعبئات بانتظار التحقق.':active?'لا توجد نقاط تطابق عوامل التصفية الحالية.':'لا توجد نقاط إطعام مسجلة حتى الآن.';return <div dir="rtl" className="space-y-5"><PageHeader title="نقاط الإطعام" description="مراجعة طلبات إضافة النقاط والتحقق من عمليات إعادة التعبئة وإدارة النقاط المنشورة." breadcrumbs={[{label:'الرئيسية',href:'/dashboard'},{label:'نقاط الإطعام'}]} actions={<div className="flex h-9 rounded-xl border border-border/45 bg-white p-1"><Button size="sm" variant={view==='LIST'?'primary':'ghost'} className="h-7 rounded-lg px-2.5" onClick={()=>setView('LIST')}><List className="size-4"/>القائمة</Button><Button size="sm" variant={view==='MAP'?'primary':'ghost'} className="h-7 rounded-lg px-2.5" onClick={()=>setView('MAP')}><Map className="size-4"/>الخريطة</Button></div>}/><FeedingPointSummaryCards summary={summary.data} loading={summary.isLoading} onFilter={update}/><FeedingPointFilterBar filters={filters} governorates={governorates.length?governorates:['دمشق','حلب','حمص','اللاذقية','طرطوس','درعا','حماة','ريف دمشق']} onChange={update} onClear={clear} active={active}/>{query.isError?<ErrorState description={query.error.message} onRetry={()=>void query.refetch()}/>:view==='MAP'?<FeedingPointsMapView items={query.data?.items??[]}/>:<FeedingPointsTable items={query.data?.items??[]} total={query.data?.total??0} pageCount={query.data?.pageCount??1} filters={filters} loading={query.isLoading||query.isFetching&&!query.data} onRetry={()=>void query.refetch()} onQueryChange={onState} emptyState={<EmptyState title={emptyTitle} description={active?'عدّل عوامل التصفية أو امسحها.':'ستظهر هنا طلبات إضافة نقاط الإطعام عند تقديمها.'} action={active?<Button variant="secondary" onClick={clear}>مسح الفلاتر</Button>:undefined}/>}/>}</div>}
