import type { Organization, OrganizationAssignmentOption } from '../types';
const now=Date.now(); const daysAgo=(d:number)=>new Date(now-d*86_400_000).toISOString();
const hours=(open24Hours=false)=>['SATURDAY','SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY'].map((day,index)=>({day:day as 'SATURDAY'|'SUNDAY'|'MONDAY'|'TUESDAY'|'WEDNESDAY'|'THURSDAY'|'FRIDAY',closed:index===6&&!open24Hours,open24Hours,opensAt:open24Hours?undefined:'09:00',closesAt:open24Hours?undefined:'17:00'}));
const docs=(id:string,mode:'VERIFIED'|'PENDING'|'MIXED')=>[
{id:`${id}-license`,type:'LICENSE' as const,name:'ترخيص الجمعية.pdf',url:'#',status:mode==='VERIFIED'?'VERIFIED' as const:mode==='PENDING'?'PENDING' as const:'VERIFIED' as const,uploadedAt:daysAgo(12),required:true},
{id:`${id}-registration`,type:'REGISTRATION' as const,name:'بيان التسجيل.pdf',url:'#',status:mode==='VERIFIED'?'VERIFIED' as const:'PENDING' as const,uploadedAt:daysAgo(11),required:true},
{id:`${id}-rep`,type:'REPRESENTATIVE_ID' as const,name:'هوية الممثل.pdf',url:'#',status:mode==='VERIFIED'?'VERIFIED' as const:mode==='MIXED'?'REJECTED' as const:'PENDING' as const,uploadedAt:daysAgo(10),required:true,rejectionReason:mode==='MIXED'?'الصورة غير واضحة':undefined},
{id:`${id}-address`,type:'ADDRESS_PROOF' as const,name:'إثبات العنوان.pdf',url:'#',status:mode==='VERIFIED'?'VERIFIED' as const:'PENDING' as const,uploadedAt:daysAgo(9),required:true},
];
export const organizationFixtures:Organization[]=[
{id:'ORG-001',name:'جمعية الرحمة للحيوان',shortName:'الرحمة',description:'جمعية سورية متخصصة بإنقاذ الحيوانات والإيواء والتبني المسؤول.',status:'ACTIVE',verificationStatus:'VERIFIED',registrationNumber:'REG-DAM-2019-114',licenseNumber:'LIC-1148',foundedYear:2019,governorate:'دمشق',city:'المزة',address:'دمشق — المزة، شارع فرعي قرب الجلاء',latitude:33.501,longitude:36.251,phone:'+963 944 560 121',email:'ops@rahma-rescue.sy',website:'https://example.org/rahma',primaryContact:{name:'ريم خضور',role:'المديرة التنفيذية',phone:'+963 944 560 121',email:'reem@example.org'},services:[{key:'RESCUE'},{key:'SHELTER'},{key:'ADOPTION'},{key:'TRANSPORT'}],operatingHours:hours(true),documents:docs('ORG-001','VERIFIED'),createdAt:daysAgo(420),updatedAt:daysAgo(2)},
{id:'ORG-002',name:'جمعية رفق دمشق',description:'جهة رعاية وإنقاذ تعمل في دمشق وريفها وتدير برنامج تبنٍ مسؤول.',status:'ACTIVE',verificationStatus:'VERIFIED',registrationNumber:'REG-DAM-2020-208',licenseNumber:'LIC-1320',foundedYear:2020,governorate:'دمشق',city:'ركن الدين',address:'دمشق — ركن الدين',latitude:33.535,longitude:36.292,phone:'+963 933 440 821',email:'contact@rifq.example.org',primaryContact:{name:'هالة سمعان',role:'منسقة العمليات',phone:'+963 933 440 821'},services:[{key:'RESCUE'},{key:'FOSTER'},{key:'ADOPTION'},{key:'AWARENESS'}],operatingHours:hours(),documents:docs('ORG-002','VERIFIED'),createdAt:daysAgo(360),updatedAt:daysAgo(1)},
{id:'ORG-003',name:'فريق أمان للإنقاذ',description:'فريق إنقاذ ميداني في حلب يركز على البلاغات الطارئة والنقل الآمن.',status:'ACTIVE',verificationStatus:'VERIFIED',registrationNumber:'REG-ALE-2021-077',licenseNumber:'LIC-1882',foundedYear:2021,governorate:'حلب',city:'الفرقان',address:'حلب — الفرقان',latitude:36.207,longitude:37.122,phone:'+963 955 820 204',email:'aman@rescue.example.org',primaryContact:{name:'سامر حموي',role:'منسق الفريق',phone:'+963 955 820 204'},services:[{key:'RESCUE'},{key:'TRANSPORT'}],operatingHours:hours(true),documents:docs('ORG-003','VERIFIED'),createdAt:daysAgo(280),updatedAt:daysAgo(3)},
{id:'ORG-004',name:'مبادرة رعاية حمص',description:'مبادرة محلية للرعاية المؤقتة والإنقاذ والدعم الغذائي.',status:'ACTIVE',verificationStatus:'VERIFIED',registrationNumber:'REG-HOM-2022-041',licenseNumber:'LIC-2077',foundedYear:2022,governorate:'حمص',city:'الوعر',address:'حمص — الوعر',latitude:34.742,longitude:36.676,phone:'+963 934 316 570',email:'homs-care@example.org',primaryContact:{name:'علاء عيسى',role:'الممثل المسؤول'},services:[{key:'RESCUE'},{key:'FOSTER'},{key:'FOOD_SUPPORT'}],operatingHours:hours(),documents:docs('ORG-004','VERIFIED'),createdAt:daysAgo(230),updatedAt:daysAgo(5)},
{id:'ORG-005',name:'فريق أصدقاء الحيوان - الساحل',shortName:'أصدقاء الحيوان',description:'جهة تطوعية منظمة تغطي اللاذقية وطرطوس في الإنقاذ والرعاية والتبني.',status:'ACTIVE',verificationStatus:'VERIFIED',registrationNumber:'REG-LAT-2020-091',licenseNumber:'LIC-1503',foundedYear:2020,governorate:'اللاذقية',city:'الزراعة',address:'اللاذقية — الزراعة',latitude:35.532,longitude:35.791,phone:'+963 945 229 118',email:'coast-friends@example.org',primaryContact:{name:'دانا قاسم',role:'مسؤولة التنسيق'},services:[{key:'RESCUE'},{key:'SHELTER'},{key:'ADOPTION'},{key:'TRANSPORT'}],operatingHours:hours(),documents:docs('ORG-005','VERIFIED'),createdAt:daysAgo(390),updatedAt:daysAgo(1)},
{id:'ORG-006',name:'مبادرة كفوف درعا',description:'مبادرة للإنقاذ والإيواء المؤقت في درعا.',status:'ACTIVE',verificationStatus:'VERIFIED',registrationNumber:'REG-DAR-2026-014',foundedYear:2024,governorate:'درعا',city:'المحطة',address:'درعا — المحطة',latitude:32.626,longitude:36.107,phone:'+963 956 340 412',email:'paws-daraa@example.org',primaryContact:{name:'نغم الحريري',role:'الممثلة المسؤولة'},services:[{key:'RESCUE'},{key:'FOSTER'}],operatingHours:hours(),documents:docs('ORG-006','VERIFIED'),createdAt:daysAgo(18),updatedAt:daysAgo(1)},
{id:'ORG-011',name:'جمعية أصدقاء الحيوان بحلب',description:'طلب انضمام قيد المراجعة والتحقق من المستندات.',status:'PENDING_VERIFICATION',verificationStatus:'IN_REVIEW',registrationNumber:'REG-ALE-2026-044',governorate:'حلب',city:'الجميلية',address:'حلب — الجميلية',phone:'+963 944 771 210',email:'aleppo-friends@example.org',primaryContact:{name:'رنا خليل',role:'ممثلة الجمعية'},services:[{key:'RESCUE'},{key:'SHELTER'},{key:'ADOPTION'}],operatingHours:hours(),documents:docs('ORG-011','PENDING'),createdAt:daysAgo(9),updatedAt:daysAgo(1)},
{id:'ORG-007',name:'جمعية بيت الحيوان',description:'طلب انضمام جديد من ريف دمشق.',status:'PENDING_VERIFICATION',verificationStatus:'NOT_REVIEWED',registrationNumber:'REG-RIF-2026-033',governorate:'ريف دمشق',city:'جرمانا',address:'جرمانا — الساحة الجديدة',phone:'+963 935 882 710',email:'animal-house@example.org',primaryContact:{name:'سوسن حيدر',role:'رئيسة الجمعية'},services:[{key:'SHELTER'},{key:'ADOPTION'}],operatingHours:hours(),documents:docs('ORG-007','PENDING').slice(0,3),createdAt:daysAgo(6),updatedAt:daysAgo(1)},
{id:'ORG-008',name:'مبادرة أمانة الساحل',description:'طلب يحتاج استكمال مستندات الترخيص.',status:'PENDING_VERIFICATION',verificationStatus:'MORE_INFO_REQUIRED',registrationNumber:'REG-TAR-2026-018',governorate:'طرطوس',city:'المدينة',address:'طرطوس — وسط المدينة',phone:'+963 932 441 220',email:'amana-coast@example.org',primaryContact:{name:'مروان شاهين',role:'ممثل المبادرة'},services:[{key:'RESCUE'},{key:'FOOD_SUPPORT'}],operatingHours:hours(),documents:docs('ORG-008','MIXED'),createdAt:daysAgo(15),updatedAt:daysAgo(2)},
{id:'ORG-010',name:'جمعية حماية الحيوان بحمص',description:'جمعية موثقة تم تعليقها تشغيلياً مع الاحتفاظ بسجلها التاريخي.',status:'SUSPENDED',verificationStatus:'VERIFIED',registrationNumber:'REG-HOM-2021-061',licenseNumber:'LIC-1730',foundedYear:2021,governorate:'حمص',city:'الإنشاءات',address:'حمص — الإنشاءات',phone:'+963 933 118 900',email:'homs-protect@example.org',primaryContact:{name:'ميس علوش',role:'مديرة الجمعية'},services:[{key:'SHELTER'},{key:'ADOPTION'}],operatingHours:hours(),documents:docs('ORG-010','VERIFIED'),createdAt:daysAgo(310),updatedAt:daysAgo(8)},
{id:'ORG-009',name:'جمعية الرفق المجتمعي',description:'طلب تم رفضه بعد تعذر التحقق من البيانات المقدمة.',status:'REJECTED',verificationStatus:'REJECTED',registrationNumber:'REG-HAM-2026-009',governorate:'حماة',city:'الحاضر',address:'حماة — الحاضر',phone:'+963 944 998 411',email:'community-kind@example.org',primaryContact:{name:'فادي محمد',role:'ممثل الطلب'},services:[{key:'AWARENESS'}],operatingHours:hours(),documents:docs('ORG-009','MIXED'),createdAt:daysAgo(32),updatedAt:daysAgo(20)},
];
export const getOrganizationFixture=(id:string)=>organizationFixtures.find(o=>o.id===id);
export const assignmentOrganizationFixtures:OrganizationAssignmentOption[]=organizationFixtures.filter(o=>o.status==='ACTIVE'&&o.verificationStatus==='VERIFIED').map((o,index)=>({id:o.id,name:o.name,governorate:o.governorate,distanceKm:[4.2,7.8,5.1,9.4,11.2][index],activeReports:[3,5,2,4,6][index]??1,availability:index===1||index===4?'LIMITED':'AVAILABLE'}));
