import { format, eachDayOfInterval } from 'date-fns';
import { getReports } from '@/features/reports/services/reports.mock';
import { getRescueMissions } from '@/features/report-operations/services/report-operations.mock';
import { getAdoptionRequests } from '@/features/adoption-requests/services/adoption-requests.mock';
import { getOrganizations } from '@/features/organizations/services/organizations.mock';
import { getUsers } from '@/features/users/services/users.mock';
import { getDonations } from '@/features/donations/services/donations.mock';
import { getFeedingPoints } from '@/features/feeding-points/services/feeding-points.mock';
import { getSupportTickets } from '@/features/support/services/support.mock';
import { reportStatusLabels, reportSeverityLabels, animalTypeLabels } from '@/features/reports/constants';
import { adoptionAnimalSpeciesLabels } from '@/features/adoption-requests/constants';
import { donationPurposeLabels, donationBeneficiaryLabels } from '@/features/donations/constants';
import type { AnalyticsFilters, AnalyticsResponse, NamedValue, OrganizationPerformanceRow } from '../types';
import { average, comparison, daysBetween, median, minutesBetween, previousRange } from '../utils';
import { operationalTargets } from '../constants';

const page={search:'',page:1,pageSize:500} as const;
const countBy=<T>(items:T[],key:(item:T)=>string)=>{const map=new Map<string,number>();items.forEach(item=>map.set(key(item),(map.get(key(item))??0)+1));return map};
const named=(map:Map<string,number>,label:(key:string)=>string):NamedValue[]=>[...map.entries()].map(([key,value])=>({key,label:label(key),value})).sort((a,b)=>b.value-a.value);
const percent=(part:number,total:number)=>total?part/total*100:0;
const inside=(value:string,from:string,to:string)=>{const time=new Date(value).getTime();return time>=new Date(`${from}T00:00:00`).getTime()&&time<=new Date(`${to}T23:59:59`).getTime()};
const metricChange=(current:number,previous:number,meaning:'HIGHER_IS_BETTER'|'LOWER_IS_BETTER'|'NEUTRAL')=>comparison(current,previous,meaning);

export async function getAnalytics(filters:AnalyticsFilters, includeDonations:boolean, includeSupport:boolean):Promise<AnalyticsResponse>{
 const prev=previousRange(filters);
 const [reportResult,prevReportResult,missionResult,prevMissionResult,adoptionResult,prevAdoptionResult,orgResult,userResult,prevUserResult,feedingResult,supportResult,donationResult]=await Promise.all([
  getReports({...page,dateFrom:filters.from,dateTo:filters.to,governorate:filters.governorate,organizationId:filters.organizationId,animalType:filters.species,severity:filters.severity}),
  getReports({...page,dateFrom:prev.from,dateTo:prev.to,governorate:filters.governorate,organizationId:filters.organizationId,animalType:filters.species,severity:filters.severity}),
  getRescueMissions({...page,dateFrom:filters.from,dateTo:filters.to,governorate:filters.governorate,organizationId:filters.organizationId}),
  getRescueMissions({...page,dateFrom:prev.from,dateTo:prev.to,governorate:filters.governorate,organizationId:filters.organizationId}),
  getAdoptionRequests({...page,dateFrom:filters.from,dateTo:filters.to,organizationId:filters.organizationId,species:filters.species}),
  getAdoptionRequests({...page,dateFrom:prev.from,dateTo:prev.to,organizationId:filters.organizationId,species:filters.species}),
  getOrganizations({...page,governorate:filters.governorate}),
  getUsers({...page,dateFrom:filters.from,dateTo:filters.to,governorate:filters.governorate}),
  getUsers({...page,dateFrom:prev.from,dateTo:prev.to,governorate:filters.governorate}),
  getFeedingPoints({...page,governorate:filters.governorate}),
  includeSupport?getSupportTickets({...page,dateFrom:filters.from,dateTo:filters.to}):Promise.resolve({items:[],total:0,page:1,pageSize:500,pageCount:1}),
  includeDonations?getDonations({...page,dateFrom:filters.from,dateTo:filters.to,organizationId:filters.organizationId}):Promise.resolve({items:[],total:0,page:1,pageSize:500,pageCount:1}),
 ]);
 const reports=reportResult.items,prevReports=prevReportResult.items,missions=missionResult.items,prevMissions=prevMissionResult.items,adoptions=adoptionResult.items,prevAdoptions=prevAdoptionResult.items,orgs=orgResult.items,users=userResult.items,prevUsers=prevUserResult.items,support=supportResult.items,donations=donationResult.items;
 const completedReports=reports.filter(r=>['RESCUED','CLOSED'].includes(r.status));const prevCompletedReports=prevReports.filter(r=>['RESCUED','CLOSED'].includes(r.status));
 const completedMissions=missions.filter(m=>m.status==='COMPLETED'),prevCompletedMissions=prevMissions.filter(m=>m.status==='COMPLETED');
 const arrival=missions.map(m=>minutesBetween(m.assignedAt,m.arrivedAt)).filter((v):v is number=>v!==undefined&&v>=0),prevArrival=prevMissions.map(m=>minutesBetween(m.assignedAt,m.arrivedAt)).filter((v):v is number=>v!==undefined&&v>=0);
 const adoptionCompleted=adoptions.filter(a=>a.status==='ADOPTED'),prevAdoptionCompleted=prevAdoptions.filter(a=>a.status==='ADOPTED');
 const activeOrgs=orgs.filter(o=>o.status==='ACTIVE'&&o.verificationStatus==='VERIFIED').length;
 const dayRange=eachDayOfInterval({start:new Date(`${filters.from}T00:00:00`),end:new Date(`${filters.to}T00:00:00`)});
 const reportTrend=dayRange.map(day=>{const key=format(day,'yyyy-MM-dd');return{date:key,primary:reports.filter(r=>r.createdAt.startsWith(key)).length,secondary:reports.filter(r=>r.closedAt?.startsWith(key)||((r.status==='RESCUED'||r.status==='CLOSED')&&r.updatedAt.startsWith(key))).length}});
 const missionTrend=dayRange.map(day=>{const key=format(day,'yyyy-MM-dd');return{date:key,primary:missions.filter(m=>m.assignedAt.startsWith(key)&&m.status!=='COMPLETED'&&m.status!=='CANCELLED').length,secondary:missions.filter(m=>m.completedAt?.startsWith(key)).length}});
 const acceptance=missions.map(m=>minutesBetween(m.assignedAt,m.acceptedAt)).filter((v):v is number=>v!==undefined&&v>=0);const duration=completedMissions.map(m=>m.completion?.durationMinutes??minutesBetween(m.assignedAt,m.completedAt)).filter((v):v is number=>v!==undefined&&v>=0);
 const orgPerformance:OrganizationPerformanceRow[]=orgs.map(org=>{const own=missions.filter(m=>m.organization.id===org.id),done=own.filter(m=>m.status==='COMPLETED');const acc=own.map(m=>minutesBetween(m.assignedAt,m.acceptedAt)).filter((v):v is number=>v!==undefined&&v>=0),arr=own.map(m=>minutesBetween(m.assignedAt,m.arrivedAt)).filter((v):v is number=>v!==undefined&&v>=0);return{id:org.id,name:org.name,governorate:org.governorate,completedMissions:done.length,activeMissions:own.filter(m=>!['COMPLETED','CANCELLED'].includes(m.status)).length,averageAcceptanceMinutes:average(acc),averageArrivalMinutes:average(arr),completionRate:percent(done.length,own.length)}}).sort((a,b)=>b.completedMissions-a.completedMissions);
 const waiting=adoptionCompleted.map(a=>daysBetween(a.submittedAt,a.adoptedAt)).filter((v):v is number=>v!==undefined&&v>=0);
 const activeUsers=users.filter(u=>u.accountStatus==='ACTIVE'&&u.lastActiveAt&&inside(u.lastActiveAt,format(new Date(new Date(`${filters.to}T23:59:59`).getTime()-29*86400000),'yyyy-MM-dd'),filters.to));
 const geographyNames=new Set([...reports.map(r=>r.governorate),...missions.map(m=>m.location.governorate),...orgs.map(o=>o.governorate),...feedingResult.items.map(f=>f.location.governorate)]);
 const reportGov=countBy(reports,r=>r.governorate),missionGov=countBy(missions,m=>m.location.governorate),orgGov=countBy(orgs,o=>o.governorate),feedingGov=countBy(feedingResult.items,f=>f.location.governorate);
 const gaps=[...geographyNames].map(governorate=>{const rr=reports.filter(r=>r.governorate===governorate),mm=missions.filter(m=>m.location.governorate===governorate),oo=orgs.filter(o=>o.governorate===governorate&&o.status==='ACTIVE').length,arr=mm.map(m=>minutesBetween(m.assignedAt,m.arrivedAt)).filter((v):v is number=>v!==undefined&&v>=0);const critical=rr.filter(r=>r.severity==='CRITICAL').length;return{governorate,reports:rr.length,criticalReports:critical,activeOrganizations:oo,averageArrivalMinutes:average(arr),note:rr.length>=3&&oo<=1?'ضغط بلاغات مرتفع مقارنة بعدد الجمعيات النشطة':critical>0&&(average(arr)??0)>operationalTargets.missionArrivalMinutes?'حالات حرجة مع زمن وصول أعلى من الهدف الداخلي':'لا توجد فجوة بارزة ضمن بيانات الفترة'}}).filter(g=>g.note!=='لا توجد فجوة بارزة ضمن بيانات الفترة');
 const reportReviewOverTarget=reports.filter(r=>{const end=r.verifiedAt??r.updatedAt;return minutesBetween(r.createdAt,end)!>operationalTargets.reportReviewMinutes&&!['NEW','UNDER_REVIEW'].includes(r.status)}).length;
 const supportOver=support.filter(t=>{const first=t.firstResponseAt?minutesBetween(t.createdAt,t.firstResponseAt):minutesBetween(t.createdAt,t.updatedAt);return first!==undefined&&first>operationalTargets.supportFirstResponseMinutes}).length;
 const donationTotals=['SYP'].map(currency=>{const own=donations.filter(d=>d.currency===currency&&['COMPLETED','REFUNDED'].includes(d.status));const amount=own.reduce((sum,d)=>sum+d.amountMinor,0);return{currency:currency as 'SYP',amountMinor:amount,operations:own.length,averageMinor:own.length?Math.round(amount/own.length):0}}).filter(x=>x.operations>0);
 const donationTrend=dayRange.map(day=>{const key=format(day,'yyyy-MM-dd'),today=donations.filter(d=>d.createdAt.startsWith(key)&&['COMPLETED','REFUNDED'].includes(d.status));return{date:key,SYP:today.reduce((s,d)=>s+d.amountMinor,0)}});
 return{
  filters,
  overview:{reports:metricChange(reports.length,prevReports.length,'NEUTRAL'),reportCompletionRate:metricChange(percent(completedReports.length,reports.length),percent(prevCompletedReports.length,prevReports.length),'HIGHER_IS_BETTER'),averageArrivalMinutes:metricChange(average(arrival)??0,average(prevArrival)??0,'LOWER_IS_BETTER'),completedMissions:metricChange(completedMissions.length,prevCompletedMissions.length,'HIGHER_IS_BETTER'),completedAdoptions:metricChange(adoptionCompleted.length,prevAdoptionCompleted.length,'HIGHER_IS_BETTER'),activeOrganizations:comparison(activeOrgs,undefined,'HIGHER_IS_BETTER'),newUsers:metricChange(users.length,prevUsers.length,'HIGHER_IS_BETTER')},
  reports:{total:reports.length,critical:reports.filter(r=>r.severity==='CRITICAL').length,completed:completedReports.length,rejected:reports.filter(r=>r.status==='REJECTED').length,averagePerDay:reports.length/Math.max(1,dayRange.length),trend:reportTrend,byStatus:named(countBy(reports,r=>r.status),k=>reportStatusLabels[k as keyof typeof reportStatusLabels]??k),bySeverity:named(countBy(reports,r=>r.severity),k=>reportSeverityLabels[k as keyof typeof reportSeverityLabels]??k),bySpecies:named(countBy(reports,r=>r.animalType),k=>animalTypeLabels[k as keyof typeof animalTypeLabels]??k),byGovernorate:named(reportGov,k=>k),funnel:[{key:'received',label:'بلاغات مستلمة',value:reports.length},{key:'verified',label:'تم التحقق منها',value:reports.filter(r=>r.verifiedAt).length},{key:'assigned',label:'تم إسنادها',value:reports.filter(r=>r.assignedAt).length},{key:'mission',label:'بدأت مهمة إنقاذ',value:reports.filter(r=>missions.some(m=>m.reportId===r.id)).length},{key:'completed',label:'اكتملت المهمة',value:reports.filter(r=>missions.some(m=>m.reportId===r.id&&m.status==='COMPLETED')).length}]},
  rescue:{total:missions.length,completed:completedMissions.length,cancelled:missions.filter(m=>m.status==='CANCELLED').length,averageAcceptanceMinutes:average(acceptance),averageArrivalMinutes:average(arrival),averageDurationMinutes:average(duration),completionRate:percent(completedMissions.length,missions.length),trend:missionTrend,organizations:orgPerformance},
  adoption:{total:adoptions.length,underReview:adoptions.filter(a=>a.status==='PENDING_REVIEW').length,approved:adoptions.filter(a=>a.status==='PUBLISHED').length,rejected:adoptions.filter(a=>a.status==='REJECTED').length,completed:adoptionCompleted.length,cancelled:0,completionRate:percent(adoptionCompleted.length,adoptions.length),funnel:[{key:'submitted',label:'عروض مقدمة للنشر',value:adoptions.length},{key:'review',label:'تمت مراجعتها',value:adoptions.filter(a=>a.status!=='PENDING_REVIEW').length},{key:'approved',label:'تم نشرها',value:adoptions.filter(a=>['PUBLISHED','ADOPTED'].includes(a.status)).length},{key:'completed',label:'اكتمل التبني',value:adoptionCompleted.length}],completedBySpecies:named(countBy(adoptionCompleted,a=>a.animal.species),k=>adoptionAnimalSpeciesLabels[k as keyof typeof adoptionAnimalSpeciesLabels]??k),averageWaitingDays:average(waiting),medianWaitingDays:median(waiting)},
  users:{total:users.length,newUsers:users.length,activeUsers:activeUsers.length,suspended:users.filter(u=>u.accountStatus==='SUSPENDED').length,reportedUsers:users.filter(u=>(u.statistics?.reportsCount??0)>0).length,adoptionUsers:users.filter(u=>(u.statistics?.adoptionRequestsCount??0)>0).length,completedAdoptionUsers:users.filter(u=>(u.statistics?.completedAdoptionsCount??0)>0).length,growth:dayRange.map(day=>{const key=format(day,'yyyy-MM-dd');return{date:key,primary:users.filter(u=>u.createdAt.startsWith(key)).length}})},
  donations:includeDonations?{totals:donationTotals,byPurpose:named(countBy(donations,d=>d.purpose),k=>donationPurposeLabels[k as keyof typeof donationPurposeLabels]??k),byBeneficiary:named(countBy(donations,d=>d.beneficiary.type),k=>donationBeneficiaryLabels[k as keyof typeof donationBeneficiaryLabels]??k),trend:donationTrend}:undefined,
  geography:{reports:named(reportGov,k=>k),missions:named(missionGov,k=>k),organizations:named(orgGov,k=>k),feedingPoints:named(feedingGov,k=>k),gaps},
  quality:{reportReviewOverTarget,missionAcceptanceOverTarget:acceptance.filter(v=>v>operationalTargets.missionAcceptanceMinutes).length,missionArrivalOverTarget:arrival.filter(v=>v>operationalTargets.missionArrivalMinutes).length,adoptionReviewOverTarget:adoptions.filter(a=>a.status==='PENDING_REVIEW'&&minutesBetween(a.submittedAt,a.updatedAt)!>operationalTargets.adoptionReviewHours*60).length,supportFirstResponseOverTarget:supportOver},generatedAt:new Date().toISOString()
 };
}

export async function getFinanceAnalytics(filters:AnalyticsFilters):Promise<AnalyticsResponse>{
 const donationResult=await getDonations({...page,dateFrom:filters.from,dateTo:filters.to,organizationId:filters.organizationId});
 const donations=donationResult.items;const dayRange=eachDayOfInterval({start:new Date(`${filters.from}T00:00:00`),end:new Date(`${filters.to}T00:00:00`)});
 const totals=['SYP'].map(currency=>{const own=donations.filter(d=>d.currency===currency&&['COMPLETED','REFUNDED'].includes(d.status));const amount=own.reduce((sum,d)=>sum+d.amountMinor,0);return{currency:currency as 'SYP',amountMinor:amount,operations:own.length,averageMinor:own.length?Math.round(amount/own.length):0}}).filter(x=>x.operations>0);
 const emptyMetric=comparison(0,undefined,'NEUTRAL');
 return{filters,overview:{reports:emptyMetric,reportCompletionRate:emptyMetric,averageArrivalMinutes:emptyMetric,completedMissions:emptyMetric,completedAdoptions:emptyMetric,activeOrganizations:emptyMetric,newUsers:emptyMetric},reports:{total:0,critical:0,completed:0,rejected:0,averagePerDay:0,trend:[],byStatus:[],bySeverity:[],bySpecies:[],byGovernorate:[],funnel:[]},rescue:{total:0,completed:0,cancelled:0,completionRate:0,trend:[],organizations:[]},adoption:{total:0,underReview:0,approved:0,rejected:0,completed:0,cancelled:0,completionRate:0,funnel:[],completedBySpecies:[]},users:{total:0,newUsers:0,activeUsers:0,suspended:0,reportedUsers:0,adoptionUsers:0,completedAdoptionUsers:0,growth:[]},donations:{totals,byPurpose:named(countBy(donations,d=>d.purpose),k=>donationPurposeLabels[k as keyof typeof donationPurposeLabels]??k),byBeneficiary:named(countBy(donations,d=>d.beneficiary.type),k=>donationBeneficiaryLabels[k as keyof typeof donationBeneficiaryLabels]??k),trend:dayRange.map(day=>{const key=format(day,'yyyy-MM-dd'),today=donations.filter(d=>d.createdAt.startsWith(key)&&['COMPLETED','REFUNDED'].includes(d.status));return{date:key,SYP:today.reduce((s,d)=>s+d.amountMinor,0)}})},geography:{reports:[],missions:[],organizations:[],feedingPoints:[],gaps:[]},quality:{reportReviewOverTarget:0,missionAcceptanceOverTarget:0,missionArrivalOverTarget:0,adoptionReviewOverTarget:0,supportFirstResponseOverTarget:0},generatedAt:new Date().toISOString()};
}
