import { apiClient } from '@/services/api/client';
import type { AuditAction, AuditEvent, AuditFilters, AuditListResult, AuditResourceType, AuditSummary } from '../types';
type R=Record<string,unknown>;
const rec=(v:unknown):R=>v&&typeof v==='object'&&!Array.isArray(v)?v as R:{};
const arr=(v:unknown):unknown[]=>Array.isArray(v)?v:[];
const str=(...v:unknown[]):string|undefined=>v.find(x=>typeof x==='string'&&x.trim()) as string|undefined;
const num=(...v:unknown[]):number|undefined=>{for(const x of v){const n=typeof x==='number'?x:typeof x==='string'?Number(x):NaN;if(Number.isFinite(n))return n;}return undefined;};
const id=(...v:unknown[])=>String(v.find(x=>x!==null&&x!==undefined&&String(x).trim())??'');
const unwrap=(v:unknown):unknown=>{const r=rec(v);return r.data??r.result??r.value??v;};
const qs=(o:Record<string,unknown>)=>{const p=new URLSearchParams();Object.entries(o).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')p.set(k,String(v));});const s=p.toString();return s?`?${s}`:'';};
function event(v:unknown):AuditEvent{const r=rec(v),a=rec(r.actor??r.user??r.admin),res=rec(r.resource??r.entity),ctx=rec(r.requestContext??r.context),meta=rec(r.metadata);const action=(str(r.action,r.eventType,r.operation)??'SYSTEM_SETTING_CHANGED') as AuditAction;const resourceType=(str(res.type,r.resourceType,r.entityType)??'SYSTEM_SETTING') as AuditResourceType;return{id:id(r.id,r.auditId,r.eventId),actor:{type:String(a.type??r.actorType??'ADMIN').toUpperCase()==='SYSTEM'?'SYSTEM':'ADMIN',id:id(a.id,r.actorId)||undefined,name:str(a.name,a.fullName,r.actorName)??'النظام',role:str(a.role,r.actorRole)},action,resource:{type:resourceType,id:id(res.id,r.resourceId,r.entityId),label:str(res.label,res.name,r.resourceLabel)},timestamp:str(r.timestamp,r.createdAt,r.creationTime)??new Date().toISOString(),reason:str(r.reason,r.description),previousValue:(r.previousValue??r.oldValue) as AuditEvent['previousValue'],newValue:(r.newValue??r.currentValue) as AuditEvent['newValue'],metadata:Object.keys(meta).length?meta as AuditEvent['metadata']:undefined,requestContext:Object.keys(ctx).length?{ipAddress:str(ctx.ipAddress,r.ipAddress),userAgent:str(ctx.userAgent,r.userAgent),correlationId:str(ctx.correlationId,r.correlationId,r.traceId)}:undefined};}
export async function getAuditEvents(f:AuditFilters,signal?:AbortSignal):Promise<AuditListResult>{const p=unwrap(await apiClient.get<unknown>(`/api/dashboard/audit-events${qs({search:f.search,action:f.action,resourceType:f.resourceType,actorId:f.actorId,from:f.from,to:f.to,page:f.page,pageSize:f.pageSize})}`,signal));const r=rec(p);let items=arr(r.items??r.events??r.auditEvents??p).map(event);if(f.actorRole)items=items.filter(x=>x.actor.role===f.actorRole);if(f.actorType)items=items.filter(x=>x.actor.type===f.actorType);if(f.resourceId)items=items.filter(x=>x.resource.id===f.resourceId);if(f.sensitive)items=items.filter(x=>Boolean(x.metadata?.destructive||x.metadata?.override));if(f.sortDirection==='asc')items=[...items].sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const total=num(r.total,r.totalCount)??items.length;return{items,total,page:f.page,pageSize:f.pageSize,pageCount:Math.max(1,num(r.pageCount)??Math.ceil(total/f.pageSize))};}
export async function getAuditEvent(eventId:string,signal?:AbortSignal){return event(unwrap(await apiClient.get<unknown>(`/api/dashboard/audit-events/${encodeURIComponent(eventId)}`,signal)));}
export async function getAuditSummary(f:Pick<AuditFilters,'from'|'to'>,signal?:AbortSignal):Promise<AuditSummary>{const p=rec(unwrap(await apiClient.get<unknown>(`/api/dashboard/audit-events/summary${qs({from:f.from,to:f.to})}`,signal)));return{total:num(p.total,p.totalCount)??0,today:num(p.today,p.todayCount)??0,sensitive:num(p.sensitive,p.sensitiveCount)??0,roleChanges:num(p.roleChanges,p.roleChangesCount)??0,settingsChanges:num(p.settingsChanges,p.settingsChangesCount)??0};}
export async function getAuditFilterOptions(signal?:AbortSignal){const p=rec(unwrap(await apiClient.get<unknown>('/api/dashboard/audit-events/filter-options',signal)));const actors=arr(p.actors).map(x=>{const q=rec(x);return{id:id(q.id,q.actorId),name:str(q.name,q.fullName)??id(q.id)}});return{actors,roles:arr(p.roles).map(String),actions:arr(p.actions).map(String) as AuditAction[],resourceTypes:arr(p.resourceTypes).map(String) as AuditResourceType[]};}
export async function getAuditExportEvents(f:AuditFilters,signal?:AbortSignal){const p=await apiClient.get<unknown>(`/api/dashboard/audit-events/export${qs({from:f.from,to:f.to})}`,signal);if(typeof p==='string'){const all=await getAuditEvents({...f,page:1,pageSize:1000},signal);return all.items;}const u=unwrap(p),r=rec(u);const rows=arr(r.items??r.events??u).map(event);if(rows.length)return rows;const all=await getAuditEvents({...f,page:1,pageSize:1000},signal);return all.items;}
