import { env } from '@/config/env';
import type { AdminSession } from '@/features/auth/session';
import type { BroadcastDraftInput, BroadcastFilters, NotificationAudience, ScheduleBroadcastInput, SendBroadcastInput, TemplateUpdateInput } from '../types';
import * as api from './notifications.api';
import * as mock from './notifications.mock';
export const getBroadcastNotifications=(f:BroadcastFilters,s?:AbortSignal)=>env.dataSource==='api'?api.getBroadcastNotifications(f,s):mock.getBroadcastNotifications(f);
export const getBroadcastNotification=(id:string,s?:AbortSignal)=>env.dataSource==='api'?api.getBroadcastNotification(id,s):mock.getBroadcastNotification(id);
export const getNotificationSummary=(s?:AbortSignal)=>env.dataSource==='api'?api.getNotificationSummary(s):mock.getNotificationSummary();
export const getNotificationTemplates=(s?:AbortSignal)=>env.dataSource==='api'?api.getNotificationTemplates(s):mock.getNotificationTemplates();
export const getNotificationTemplate=(k:string,s?:AbortSignal)=>env.dataSource==='api'?api.getNotificationTemplate(k,s):mock.getNotificationTemplate(k);
export const getNotificationTargetSources=(s?:AbortSignal)=>env.dataSource==='api'?api.getNotificationTargetSources(s):mock.getNotificationTargetSources();
export const estimateNotificationAudience=(a:NotificationAudience,s?:AbortSignal)=>env.dataSource==='api'?api.estimateNotificationAudience(a,s):mock.estimateNotificationAudience(a);
export const createBroadcastDraft=(i:BroadcastDraftInput,a:AdminSession)=>env.dataSource==='api'?api.createBroadcastDraft(i,a):mock.createBroadcastDraft(i,a);
export const sendBroadcast=(i:SendBroadcastInput,a:AdminSession)=>env.dataSource==='api'?api.sendBroadcast(i,a):mock.sendBroadcast(i,a);
export const scheduleBroadcast=(i:ScheduleBroadcastInput,a:AdminSession)=>env.dataSource==='api'?api.scheduleBroadcast(i,a):mock.scheduleBroadcast(i,a);
export const sendExistingBroadcast=(id:string,a:AdminSession)=>env.dataSource==='api'?api.sendExistingBroadcast(id,a):mock.sendExistingBroadcast(id,a);
export const scheduleExistingBroadcast=(id:string,t:string,a:AdminSession)=>env.dataSource==='api'?api.scheduleExistingBroadcast(id,t,a):mock.scheduleExistingBroadcast(id,t,a);
export const cancelBroadcast=(id:string,a:AdminSession)=>env.dataSource==='api'?api.cancelBroadcast(id,a):mock.cancelBroadcast(id,a);
export const duplicateBroadcast=(id:string,a:AdminSession)=>env.dataSource==='api'?api.duplicateBroadcast(id,a):mock.duplicateBroadcast(id,a);
export const updateNotificationTemplate=(k:string,i:TemplateUpdateInput)=>env.dataSource==='api'?api.updateNotificationTemplate(k,i):mock.updateNotificationTemplate(k,i);
