import type { AdminSession } from '@/features/auth/session';
import { getOrganizationFixture } from '@/features/organizations/services/organization-fixtures';
import { getUsers } from '@/features/users/services/users.mock';
import { getEditorialRecord } from '@/features/content/services/content.mock';
import { mockDelay } from '@/services/mock/delay';
import { recordAdminAuditEvent } from '@/features/audit-log/services/audit-log.mock';
import type { BroadcastDetails,BroadcastDraftInput,BroadcastFilters,BroadcastListResult,BroadcastNotification,NotificationAudience,NotificationDeliveryStatus,NotificationSummary,NotificationTemplateVariable,NotificationTimelineEvent,ScheduleBroadcastInput,SendBroadcastInput,SystemNotificationTemplate,TemplateUpdateInput } from '../types';
import { isValidNotificationDeepLink,summarizeAudience } from '../utils';
const now=Date.now(),hours=(n:number)=>new Date(now+n*3_600_000).toISOString(),days=(n:number)=>new Date(now+n*86_400_000).toISOString();
const rows:BroadcastNotification[]=[
{id:'NTF-2026-0041',title:'تنبيه بخصوص ارتفاع درجات الحرارة',body:'يرجى توفير الماء والظل للحيوانات خلال ساعات الذروة وتجنب تركها في المركبات المغلقة.',channels:['IN_APP','PUSH'],audience:{everyone:false,userTypes:['USER'],governorates:['دمشق','ريف دمشق']},deepLink:'/content/articles/ART-2026-0041',status:'SENT',sentAt:hours(-7),createdBy:{id:'mock-admin-002',name:'ليان المصري'},statistics:{targetedCount:1248,sentCount:1239,failedCount:9,openedCount:482,mockData:true},createdAt:days(-2),updatedAt:hours(-7)},
{id:'NTF-2026-0043',title:'تحديث مهم لخدمات ResQ',body:'مسودة رسالة لتوضيح تحسينات تجربة متابعة البلاغات.',channels:['IN_APP'],audience:{everyone:true},status:'DRAFT',createdBy:{id:'mock-admin-003',name:'سلمى خليل'},createdAt:hours(-5),updatedAt:hours(-2)},
{id:'NTF-2026-0044',title:'تحديث حالة طلبات التبني',body:'تم إرسال تحديث إلى المتقدمين الذين لديهم طلبات قيد المراجعة.',channels:['PUSH'],audience:{everyone:false,userTypes:['USER']},deepLink:'/adoption-requests/AD-2026-0104',status:'PARTIALLY_SENT',sentAt:days(-1),createdBy:{id:'mock-admin-001',name:'أحمد الخطيب'},statistics:{targetedCount:210,sentCount:194,failedCount:16,mockData:true},createdAt:days(-2),updatedAt:days(-1)},
{id:'NTF-2026-0045',title:'إشعار صيانة مجدولة',body:'سيتم تنفيذ أعمال صيانة قصيرة على بعض الخدمات.',channels:['IN_APP','PUSH'],audience:{everyone:true},status:'FAILED',failureReason:'تعذر بدء عملية الإرسال.',createdBy:{id:'mock-admin-004',name:'فريق المحتوى'},statistics:{targetedCount:3042,sentCount:0,failedCount:3042,mockData:true},createdAt:days(-4),updatedAt:days(-4)},
{id:'NTF-2026-0046',title:'إشعار ملغي لجمعية محددة',body:'رسالة كانت مجدولة ثم ألغيت بعد تغيير الخطة التشغيلية.',channels:['IN_APP'],audience:{everyone:false,userTypes:['ORGANIZATION'],organizationIds:['ORG-001']},status:'CANCELLED',scheduledAt:days(2),createdBy:{id:'mock-admin-001',name:'أحمد الخطيب'},createdAt:days(-3),updatedAt:days(-1)},
{id:'NTF-2026-0047',title:'تحديث توعوي قصير',body:'جاري تجهيز دفعة الإرسال التجريبية.',channels:['PUSH'],audience:{everyone:false,userTypes:['USER'],governorates:['حلب']},status:'SENDING',createdBy:{id:'mock-admin-002',name:'ليان المصري'},statistics:{targetedCount:620,sentCount:410,mockData:true},createdAt:hours(-1),updatedAt:hours(-1)},
];
const timeline=new Map<string,NotificationTimelineEvent[]>();
for(const item of rows){const events:NotificationTimelineEvent[]=[{id:`${item.id}-created`,title:'تم إنشاء الإشعار',timestamp:item.createdAt,actor:item.createdBy.name,tone:'info'}];if(item.status==='SCHEDULED')events.push({id:`${item.id}-scheduled`,title:'تمت جدولة الإرسال',timestamp:item.updatedAt,actor:item.createdBy.name,tone:'pending'});if(item.sentAt)events.push({id:`${item.id}-sent`,title:item.status==='PARTIALLY_SENT'?'تم الإرسال جزئيًا':'تم إرسال الإشعار',timestamp:item.sentAt,actor:item.createdBy.name,tone:item.status==='PARTIALLY_SENT'?'pending':'success'});if(item.status==='CANCELLED')events.push({id:`${item.id}-cancel`,title:'تم إلغاء الجدولة',timestamp:item.updatedAt,actor:item.createdBy.name,tone:'neutral'});if(item.status==='FAILED')events.push({id:`${item.id}-failed`,title:'فشل الإرسال',timestamp:item.updatedAt,tone:'critical'});timeline.set(item.id,events);}
const variables={userName:{key:'userName',label:'اسم المستخدم',example:'سارة'},reportId:{key:'reportId',label:'رقم البلاغ',example:'RQ-2026-00481'},animalName:{key:'animalName',label:'اسم الحيوان',example:'لوز'},organizationName:{key:'organizationName',label:'اسم الجمعية',example:'جمعية الرحمة للحيوان'},status:{key:'status',label:'الحالة',example:'تم التحقق'}};
const templates:SystemNotificationTemplate[]=[
{id:'TPL-REPORT-STATUS',key:'REPORT_STATUS_UPDATED',name:'تحديث حالة البلاغ',description:'يرسل عند تغير حالة بلاغ مسجل.',titleTemplate:'تحديث على بلاغك {{reportId}}',bodyTemplate:'مرحبًا {{userName}}، تم تحديث حالة البلاغ إلى {{status}}.',channels:['IN_APP','PUSH'],enabled:true,required:true,availableVariables:[variables.userName,variables.reportId,variables.status],updatedAt:days(-4)},
{id:'TPL-MISSION-ASSIGNED',key:'MISSION_ASSIGNED',name:'إسناد مهمة إنقاذ',description:'يرسل للجمعية عند إسناد مهمة إنقاذ.',titleTemplate:'مهمة إنقاذ جديدة',bodyTemplate:'تم إسناد مهمة جديدة إلى {{organizationName}} مرتبطة بالبلاغ {{reportId}}.',channels:['IN_APP','PUSH'],enabled:true,required:true,availableVariables:[variables.organizationName,variables.reportId],updatedAt:days(-8)},
{id:'TPL-MISSION-COMPLETED',key:'MISSION_COMPLETED',name:'اكتمال عملية الإنقاذ',description:'تحديث متعلق بإتمام المهمة.',titleTemplate:'اكتملت عملية الإنقاذ',bodyTemplate:'تم إكمال عملية الإنقاذ المرتبطة بالبلاغ {{reportId}}.',channels:['IN_APP'],enabled:true,required:false,availableVariables:[variables.reportId],updatedAt:days(-9)},
{id:'TPL-ADOPTION-APPROVED',key:'ADOPTION_REQUEST_APPROVED',name:'قبول طلب التبني',description:'يرسل لمقدم الطلب بعد الموافقة الإدارية.',titleTemplate:'تمت الموافقة على طلب التبني',bodyTemplate:'مرحبًا {{userName}}، تمت الموافقة على طلب تبني {{animalName}}.',channels:['IN_APP','PUSH'],enabled:true,required:true,availableVariables:[variables.userName,variables.animalName],updatedAt:days(-2)},
{id:'TPL-ADOPTION-REJECTED',key:'ADOPTION_REQUEST_REJECTED',name:'رفض طلب التبني',description:'يرسل عند رفض طلب التبني.',titleTemplate:'تحديث على طلب التبني',bodyTemplate:'مرحبًا {{userName}}، تم تحديث طلب تبني {{animalName}} إلى {{status}}.',channels:['IN_APP'],enabled:true,required:false,availableVariables:[variables.userName,variables.animalName,variables.status],updatedAt:days(-6)},
{id:'TPL-ORG-APPROVED',key:'ORGANIZATION_APPROVED',name:'اعتماد جمعية',description:'يرسل عند اعتماد جمعية.',titleTemplate:'تم اعتماد {{organizationName}}',bodyTemplate:'تم اعتماد الجهة ويمكنها الآن استخدام الخدمات المتاحة للجهات الموثقة.',channels:['IN_APP','PUSH'],enabled:true,required:false,availableVariables:[variables.organizationName],updatedAt:days(-11)},

];
const preparedTemplates:Array<{key:string;name:string;description:string;title:string;body:string;variables:NotificationTemplateVariable[]}>= [
 {key:'REPORT_CREATED',name:'استلام بلاغ جديد',description:'تأكيد استلام البلاغ للمستخدم.',title:'تم استلام بلاغك {{reportId}}',body:'مرحبًا {{userName}}، تم استلام البلاغ وسنوافيك بالتحديثات.',variables:[variables.userName,variables.reportId]},
 {key:'REPORT_ASSIGNED',name:'إسناد البلاغ',description:'تحديث عند إسناد البلاغ إلى جهة.',title:'تم إسناد البلاغ {{reportId}}',body:'تم إسناد البلاغ إلى {{organizationName}}.',variables:[variables.reportId,variables.organizationName]},
 {key:'REPORT_COMPLETED',name:'اكتمال حالة البلاغ',description:'تحديث نهائي عند اكتمال معالجة البلاغ.',title:'اكتملت متابعة البلاغ {{reportId}}',body:'تم تحديث البلاغ إلى {{status}}.',variables:[variables.reportId,variables.status]},
 {key:'MISSION_STATUS_UPDATED',name:'تحديث حالة مهمة الإنقاذ',description:'تحديث للجهة عند تغير مرحلة المهمة.',title:'تحديث مهمة الإنقاذ',body:'تم تحديث حالة المهمة المرتبطة بالبلاغ {{reportId}} إلى {{status}}.',variables:[variables.reportId,variables.status]},
 {key:'ADOPTION_REQUEST_RECEIVED',name:'استلام طلب التبني',description:'تأكيد استلام طلب التبني.',title:'تم استلام طلب التبني',body:'مرحبًا {{userName}}، تم استلام طلبك لتبني {{animalName}}.',variables:[variables.userName,variables.animalName]},
 {key:'ADOPTION_REQUEST_UNDER_REVIEW',name:'بدء مراجعة طلب التبني',description:'تحديث عند بدء المراجعة.',title:'بدأت مراجعة طلب التبني',body:'طلب تبني {{animalName}} قيد المراجعة الآن.',variables:[variables.animalName]},
 {key:'ADOPTION_COMPLETED',name:'اكتمال التبني',description:'يرسل بعد اكتمال التسليم.',title:'اكتملت عملية التبني',body:'نتمنى لك ولـ {{animalName}} بداية سعيدة وآمنة.',variables:[variables.animalName]},
 {key:'ORGANIZATION_REJECTED',name:'رفض طلب جمعية',description:'تحديث حالة التحقق للجمعية.',title:'تحديث على طلب انضمام {{organizationName}}',body:'تم تحديث حالة الطلب إلى {{status}}.',variables:[variables.organizationName,variables.status]},
 {key:'ORGANIZATION_MORE_INFO_REQUIRED',name:'طلب معلومات إضافية من جمعية',description:'طلب استكمال بيانات التحقق.',title:'نحتاج معلومات إضافية',body:'يرجى استكمال معلومات {{organizationName}} المطلوبة في لوحة الجهة.',variables:[variables.organizationName]},
];
for(const [index,spec] of preparedTemplates.entries())templates.push({id:`TPL-PREP-${index+1}`,key:spec.key,name:spec.name,description:spec.description,titleTemplate:spec.title,bodyTemplate:spec.body,channels:['IN_APP','PUSH'],enabled:true,required:false,availableVariables:spec.variables,updatedAt:days(-14-index)});
const clone=<T>(value:T):T=>structuredClone(value);
function estimate(a:NotificationAudience){if(a.everyone)return 3042;let total=0;if(a.userTypes?.includes('USER'))total+=1800;if(a.userTypes?.includes('ORGANIZATION'))total+=42;if(a.governorates?.length)total=Math.max(1,Math.round(total*(a.governorates.length/8)));if(a.organizationIds?.length)total=a.organizationIds.length;if(a.userIds?.length)total=a.userIds.length;return total||120;}
async function ensurePublicDeepLink(deepLink:string|undefined){if(!deepLink)return;const match=deepLink.match(/^\/content\/articles\/([A-Za-z0-9-]+)$/);if(!match)return;const id=match[1];if(!id)return;const record=await getEditorialRecord('article',id);if(record&&record.item.status!=='PUBLISHED')throw new Error('CONTENT_NOT_PUBLISHED');}
function requireRow(id:string){const row=rows.find((x)=>x.id===id);if(!row)throw new Error('NOTIFICATION_NOT_FOUND');return row;}
function addEvent(id:string,event:Omit<NotificationTimelineEvent,'id'>){timeline.set(id,[...(timeline.get(id)??[]),{id:`${id}-${Date.now()}`, ...event}]);}
export async function getBroadcastNotifications(filters:BroadcastFilters):Promise<BroadcastListResult>{await mockDelay(35);let data=[...rows];const q=filters.search.trim().toLowerCase();if(q)data=data.filter((x)=>[x.id,x.title,x.body].some((v)=>v.toLowerCase().includes(q)));if(filters.status)data=data.filter((x)=>x.status===filters.status);if(filters.channel)data=data.filter((x)=>x.channels.includes(filters.channel!));if(filters.audienceType)data=data.filter((x)=>filters.audienceType==='EVERYONE'?x.audience.everyone:x.audience.userTypes?.includes(filters.audienceType as 'USER'|'ORGANIZATION'));if(filters.creator)data=data.filter((x)=>x.createdBy.name===filters.creator);if(filters.dateFrom)data=data.filter((x)=>new Date(x.scheduledAt??x.sentAt??x.createdAt)>=new Date(filters.dateFrom!));if(filters.dateTo)data=data.filter((x)=>new Date(x.scheduledAt??x.sentAt??x.createdAt)<=new Date(`${filters.dateTo}T23:59:59`));const key=filters.sortBy??'updatedAt';data.sort((a,b)=>{const av=new Date(a[key]??a.updatedAt).getTime(),bv=new Date(b[key]??b.updatedAt).getTime();return (filters.sortDirection==='asc'?1:-1)*(av-bv);});const total=data.length,start=(filters.page-1)*filters.pageSize;return{items:clone(data.slice(start,start+filters.pageSize)),total,pageCount:Math.max(1,Math.ceil(total/filters.pageSize))};}
export async function getBroadcastNotification(id:string):Promise<BroadcastDetails>{await mockDelay(25);const b=requireRow(id);return{broadcast:clone(b),timeline:clone(timeline.get(id)??[]),audienceSummary:summarizeAudience(b.audience),estimatedAudience:estimate(b.audience)};}
export async function getNotificationSummary():Promise<NotificationSummary>{await mockDelay(20);const today=new Date().toDateString();return{scheduled:rows.filter((x)=>x.status==='SCHEDULED').length,sentToday:rows.filter((x)=>x.sentAt&&new Date(x.sentAt).toDateString()===today).length,partiallySent:rows.filter((x)=>x.status==='PARTIALLY_SENT').length,drafts:rows.filter((x)=>x.status==='DRAFT').length,activeTemplates:templates.filter((x)=>x.enabled).length};}
export async function estimateNotificationAudience(audience:NotificationAudience){await mockDelay(15);return estimate(audience);}
function create(input:BroadcastDraftInput,status:NotificationDeliveryStatus,actor:AdminSession):BroadcastNotification{if(input.deepLink&&!isValidNotificationDeepLink(input.deepLink))throw new Error('INVALID_DEEP_LINK');const timestamp=new Date().toISOString();const item:BroadcastNotification={id:`NTF-2026-${String(50+rows.length).padStart(4,'0')}`,title:input.title,body:input.body,channels:input.channels,audience:input.audience,deepLink:input.deepLink||undefined,imageUrl:input.imageUrl||undefined,status,createdBy:{id:actor.id,name:actor.name},createdAt:timestamp,updatedAt:timestamp};rows.unshift(item);timeline.set(item.id,[{id:`${item.id}-created`,title:'تم إنشاء الإشعار',timestamp,actor:actor.name,tone:'info'}]);return item;}
export async function createBroadcastDraft(input:BroadcastDraftInput,actor:AdminSession){await mockDelay(35);return clone(create(input,'DRAFT',actor));}
export async function sendBroadcast(input:SendBroadcastInput,actor:AdminSession){await mockDelay(40);await ensurePublicDeepLink(input.deepLink);const item=create(input,'SENT',actor);item.sentAt=new Date().toISOString();item.updatedAt=item.sentAt;item.statistics={targetedCount:estimate(item.audience),sentCount:estimate(item.audience),failedCount:0,mockData:true};addEvent(item.id,{title:'تم تسجيل الإرسال التجريبي',timestamp:item.sentAt,actor:actor.name,detail:'التسليم الفعلي يتطلب بنية Backend/Push.',tone:'success'});recordAdminAuditEvent(actor,{action:'NOTIFICATION_SENT',resource:{type:'NOTIFICATION',id:item.id,label:item.title},previousValue:{status:'DRAFT'},newValue:{status:'SENT'},metadata:{source:'إدارة الإشعارات'}});return clone(item);}
export async function scheduleBroadcast(input:ScheduleBroadcastInput,actor:AdminSession){await mockDelay(40);await ensurePublicDeepLink(input.deepLink);if(new Date(input.scheduledAt).getTime()<=Date.now())throw new Error('SCHEDULE_MUST_BE_FUTURE');const item=create(input,'SCHEDULED',actor);item.scheduledAt=new Date(input.scheduledAt).toISOString();item.updatedAt=new Date().toISOString();addEvent(item.id,{title:'تمت جدولة الإرسال',timestamp:item.updatedAt,actor:actor.name,detail:`موعد الجدولة: ${item.scheduledAt}`,tone:'pending'});recordAdminAuditEvent(actor,{action:'NOTIFICATION_SCHEDULED',resource:{type:'NOTIFICATION',id:item.id,label:item.title},previousValue:{status:'DRAFT'},newValue:{status:'SCHEDULED'},metadata:{source:'إدارة الإشعارات'}});return clone(item);}

export async function sendExistingBroadcast(id:string,actor:AdminSession){await mockDelay(35);const item=requireRow(id);await ensurePublicDeepLink(item.deepLink);if(item.status!=='DRAFT')throw new Error('CANNOT_SEND');item.status='SENT';item.sentAt=new Date().toISOString();item.updatedAt=item.sentAt;const count=estimate(item.audience);item.statistics={targetedCount:count,sentCount:count,failedCount:0,mockData:true};addEvent(id,{title:'تم تسجيل الإرسال التجريبي',timestamp:item.sentAt,actor:actor.name,detail:'التسليم الفعلي يتطلب Backend/Push provider.',tone:'success'});recordAdminAuditEvent(actor,{action:'NOTIFICATION_SENT',resource:{type:'NOTIFICATION',id,label:item.title},previousValue:{status:'DRAFT'},newValue:{status:'SENT'},metadata:{source:'إدارة الإشعارات'}});return clone(item);}
export async function scheduleExistingBroadcast(id:string,scheduledAt:string,actor:AdminSession){await mockDelay(35);const item=requireRow(id);await ensurePublicDeepLink(item.deepLink);if(item.status!=='DRAFT')throw new Error('CANNOT_SCHEDULE');if(new Date(scheduledAt).getTime()<=Date.now())throw new Error('SCHEDULE_MUST_BE_FUTURE');item.status='SCHEDULED';item.scheduledAt=new Date(scheduledAt).toISOString();item.updatedAt=new Date().toISOString();addEvent(id,{title:'تمت جدولة الإرسال',timestamp:item.updatedAt,actor:actor.name,detail:`موعد الجدولة: ${item.scheduledAt}`,tone:'pending'});recordAdminAuditEvent(actor,{action:'NOTIFICATION_SCHEDULED',resource:{type:'NOTIFICATION',id,label:item.title},previousValue:{status:'DRAFT'},newValue:{status:'SCHEDULED'},metadata:{source:'إدارة الإشعارات'}});return clone(item);}

export async function cancelBroadcast(id:string,actor:AdminSession){await mockDelay(30);const item=requireRow(id);if(item.status!=='SCHEDULED')throw new Error('CANNOT_CANCEL');item.status='CANCELLED';item.updatedAt=new Date().toISOString();addEvent(id,{title:'تم إلغاء الجدولة',timestamp:item.updatedAt,actor:actor.name,tone:'neutral'});recordAdminAuditEvent(actor,{action:'NOTIFICATION_CANCELLED',resource:{type:'NOTIFICATION',id,label:item.title},previousValue:{status:'SCHEDULED'},newValue:{status:'CANCELLED'},metadata:{source:'إدارة الإشعارات'}});return clone(item);}
export async function duplicateBroadcast(id:string,actor:AdminSession){await mockDelay(30);const source=requireRow(id);return clone(create({title:`نسخة من: ${source.title}`,body:source.body,channels:source.channels,audience:clone(source.audience),deepLink:source.deepLink,imageUrl:source.imageUrl},'DRAFT',actor));}
export async function getNotificationTemplates(){await mockDelay(25);return clone(templates);}
export async function getNotificationTemplate(key:string){await mockDelay(20);return clone(templates.find((x)=>x.key===key));}
function usedVariables(text:string){return Array.from(text.matchAll(/\{\{([A-Za-z0-9_]+)\}\}/g)).map((m)=>m[1]??'').filter(Boolean);}
export async function updateNotificationTemplate(key:string,input:TemplateUpdateInput){await mockDelay(30);const template=templates.find((x)=>x.key===key);if(!template)throw new Error('TEMPLATE_NOT_FOUND');const allowed=new Set(template.availableVariables.map((x)=>x.key));const unknown=[...usedVariables(input.titleTemplate),...usedVariables(input.bodyTemplate)].find((v)=>!allowed.has(v));if(unknown)throw new Error(`UNKNOWN_TEMPLATE_VARIABLE:${unknown}`);template.titleTemplate=input.titleTemplate;template.bodyTemplate=input.bodyTemplate;template.channels=[...input.channels];template.enabled=input.enabled;template.updatedAt=new Date().toISOString();return clone(template);}
export async function getNotificationTargetSources(){await mockDelay(10);const users=await getUsers({search:'',page:1,pageSize:8,sortBy:'createdAt',sortDirection:'desc'});return{organizations:['ORG-001','ORG-002','ORG-003'].map((id)=>{const x=getOrganizationFixture(id);return{id,name:x?.name??id};}),users:users.items.map((user)=>({id:user.id,name:user.fullName}))};}
