import { subDays, subMonths, startOfMonth, startOfYear, format, differenceInCalendarDays } from 'date-fns';
import type { AnalyticsFilters, AnalyticsRangePreset, ComparisonMetric, TrendDirectionMeaning } from '../types';
export function rangeDates(range:AnalyticsRangePreset,customFrom?:string,customTo?:string){const now=new Date();const to=format(now,'yyyy-MM-dd');if(range==='custom'&&customFrom&&customTo)return{from:customFrom,to:customTo};if(range==='today')return{from:to,to};if(range==='7d')return{from:format(subDays(now,6),'yyyy-MM-dd'),to};if(range==='30d')return{from:format(subDays(now,29),'yyyy-MM-dd'),to};if(range==='month')return{from:format(startOfMonth(now),'yyyy-MM-dd'),to};if(range==='3m')return{from:format(subMonths(now,3),'yyyy-MM-dd'),to};return{from:format(startOfYear(now),'yyyy-MM-dd'),to};}
export function previousRange(filters:AnalyticsFilters){const from=new Date(`${filters.from}T00:00:00`),to=new Date(`${filters.to}T23:59:59`);const days=Math.max(1,differenceInCalendarDays(to,from)+1);const prevTo=subDays(from,1),prevFrom=subDays(prevTo,days-1);return{from:format(prevFrom,'yyyy-MM-dd'),to:format(prevTo,'yyyy-MM-dd')};}
export function comparison(value:number,previousValue:number|undefined,meaning:TrendDirectionMeaning):ComparisonMetric{const percentageChange=previousValue===undefined||previousValue===0?undefined:((value-previousValue)/previousValue)*100;return{value,previousValue,percentageChange,meaning};}
export const formatInteger=(value:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(value);
export const formatPercent=(value:number)=>`${new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(value)}٪`;
export function formatDuration(minutes?:number){if(minutes===undefined||Number.isNaN(minutes))return'—';if(minutes<60)return`${Math.round(minutes)} دقيقة`;if(minutes<1440)return`${Math.floor(minutes/60)} س ${Math.round(minutes%60)} د`;return`${Math.floor(minutes/1440)} يوم`}
export function formatAnalyticsMoney(amountMinor:number,_currency:'SYP'='SYP'){return `${new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(amountMinor)} ل.س`}
export const average=(values:number[])=>values.length?values.reduce((sum,n)=>sum+n,0)/values.length:undefined;
export const median=(values:number[])=>{if(!values.length)return undefined;const sorted=[...values].sort((a,b)=>a-b),m=Math.floor(sorted.length/2);return sorted.length%2?sorted[m]!:(sorted[m-1]!+sorted[m]!)/2};
export const minutesBetween=(a?:string,b?:string)=>a&&b?(new Date(b).getTime()-new Date(a).getTime())/60000:undefined;
export const daysBetween=(a?:string,b?:string)=>a&&b?(new Date(b).getTime()-new Date(a).getTime())/86400000:undefined;
