import { memo, type ReactNode } from 'react';
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { EmptyState, SectionHeader } from '@/components/ui';
import { chartPalette } from '../constants';
import type { NamedValue, TimeSeriesPoint } from '../types';
import { formatInteger } from '../utils';

export function ChartCard({ title, description, children }: { title: string; description?: string; children: ReactNode }) {
  return <div className="rounded-xl border border-border/45 bg-white p-4 shadow-none"><SectionHeader title={title} description={description} /><div className="mt-3 h-[245px]">{children}</div></div>;
}
function TimeSeriesChartComponent({ data, primaryLabel, secondaryLabel }: { data: TimeSeriesPoint[]; primaryLabel: string; secondaryLabel?: string }) { if (!data.some((d) => d.primary || (d.secondary ?? 0))) return <EmptyState title="لا توجد بيانات كافية لهذه الفترة." description="غيّر الفترة أو عوامل التصفية لعرض الاتجاه." />; return <ResponsiveContainer width="100%" height="100%" debounce={120}><LineChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} tick={{ fontSize: 11 }} /><Tooltip formatter={(value: unknown, name: unknown) => [formatInteger(Number(value ?? 0)), String(name ?? '')]} labelFormatter={(label) => String(label)} /><Legend /><Line type="monotone" dataKey="primary" name={primaryLabel} stroke={chartPalette.primary} strokeWidth={2} dot={false} />{secondaryLabel && <Line type="monotone" dataKey="secondary" name={secondaryLabel} stroke={chartPalette.success} strokeWidth={2} dot={false} />}</LineChart></ResponsiveContainer>; }
function RankedBarChartComponent({ data, valueLabel = 'العدد' }: { data: NamedValue[]; valueLabel?: string }) { if (!data.length) return <EmptyState title="لا توجد بيانات كافية لهذه الفترة." />; return <ResponsiveContainer width="100%" height="100%" debounce={120}><BarChart data={data.slice(0, 10)} layout="vertical" margin={{ left: 12, right: 12 }}><CartesianGrid strokeDasharray="3 3" /><XAxis type="number" allowDecimals={false} /><YAxis dataKey="label" type="category" width={110} tick={{ fontSize: 11 }} /><Tooltip formatter={(value: unknown) => [formatInteger(Number(value ?? 0)), valueLabel]} /><Bar dataKey="value" name={valueLabel} fill={chartPalette.info} radius={[4, 4, 4, 4]} /></BarChart></ResponsiveContainer>; }
function DistributionChartComponent({ data }: { data: NamedValue[] }) { if (!data.length) return <EmptyState title="لا توجد بيانات كافية لهذه الفترة." />; return <ResponsiveContainer width="100%" height="100%" debounce={120}><BarChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="label" tick={{ fontSize: 10 }} /><YAxis allowDecimals={false} /><Tooltip formatter={(value: unknown) => [formatInteger(Number(value ?? 0)), 'العدد']} /><Bar dataKey="value" name="العدد" fill={chartPalette.primary} radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer>; }
function DonationTrendChartComponent({ data }: { data: Array<{ date: string; SYP: number }> }) { if (!data.some((d) => d.SYP)) return <EmptyState title="لا توجد تبرعات ضمن هذه الفترة." />; return <ResponsiveContainer width="100%" height="100%" debounce={120}><LineChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip formatter={(value: unknown) => [`${formatInteger(Number(value ?? 0))} ل.س`, 'التبرعات']} /><Line type="monotone" dataKey="SYP" name="ل.س" stroke={chartPalette.primary} strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer>; }
export const TimeSeriesChart = memo(TimeSeriesChartComponent);
export const RankedBarChart = memo(RankedBarChartComponent);
export const DistributionChart = memo(DistributionChartComponent);
export const DonationTrendChart = memo(DonationTrendChartComponent);
