import { permissionDefinitions, permissions, type Permission, type PermissionDefinition } from '@/features/auth/permissions';
import { apiClient } from '@/services/api/client';
import type {
  AdminFilters, AdminListResult, AdminRoleRecord, AdminUser, CreateRoleInput, InviteAdminInput,
  LookupType, SystemLookupItem, SystemSettings, UpdateRoleInput,
} from '../types';

type R = Record<string, unknown>;
const rec=(v:unknown):R=>v&&typeof v==='object'&&!Array.isArray(v)?v as R:{};
const arr=(v:unknown):unknown[]=>Array.isArray(v)?v:[];
const str=(...v:unknown[]):string|undefined=>v.find(x=>typeof x==='string'&&x.trim()) as string|undefined;
const num=(...v:unknown[]):number|undefined=>{for(const x of v){const n=typeof x==='number'?x:typeof x==='string'?Number(x):NaN;if(Number.isFinite(n))return n;}return undefined;};
const bool=(...v:unknown[]):boolean|undefined=>{for(const x of v){if(typeof x==='boolean')return x;if(x==='true'||x===1||x==='1')return true;if(x==='false'||x===0||x==='0')return false;}return undefined;};
const id=(...v:unknown[])=>String(v.find(x=>x!==null&&x!==undefined&&String(x).trim())??'');
const unwrap=(v:unknown):unknown=>{const r=rec(v);return r.data??r.result??r.value??v;};
const iso=(...v:unknown[])=>str(...v)??new Date().toISOString();
const qs=(o:Record<string,unknown>)=>{const p=new URLSearchParams();Object.entries(o).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')p.set(k,String(v));});const s=p.toString();return s?`?${s}`:'';};

const permissionSet=new Set<string>(permissions);
const normalizePermissions=(v:unknown):Permission[]=>arr(v).map(String).filter((x):x is Permission=>permissionSet.has(x));
const roleSummary=(v:unknown)=>{const r=rec(v);const name=str(r.name,r.roleName,r.label,r.key)??'';return{id:id(r.id,r.roleId,name),key:str(r.key,r.code,name)??name,name};};
const status=(v:unknown):AdminUser['status']=>{const s=String(v??'ACTIVE').toUpperCase();return s==='SUSPENDED'||s==='INVITED'||s==='DISABLED'?s:'ACTIVE';};
function admin(v:unknown):AdminUser{const r=rec(v), creator=rec(r.createdBy??r.creator);const rs=arr(r.roles??r.roleNames??r.assignedRoles).map(x=>typeof x==='string'?{id:String(x),key:String(x),name:String(x)}:roleSummary(x));return{id:id(r.id,r.userId,r.adminUserId),fullName:str(r.fullName,r.name,r.displayName,r.email)??'',email:str(r.email)??'',avatarUrl:str(r.avatarUrl,r.avatar),status:status(r.status),roles:rs,createdAt:iso(r.createdAt,r.creationTime),updatedAt:iso(r.updatedAt,r.lastModificationTime,r.createdAt,r.creationTime),invitedAt:str(r.invitedAt),acceptedAt:str(r.acceptedAt),lastLoginAt:str(r.lastLoginAt,r.lastLogin),createdBy:Object.keys(creator).length?{id:id(creator.id,creator.userId),name:str(creator.name,creator.fullName)??'الإدارة'}:undefined,mfaEnabled:bool(r.mfaEnabled,r.isMfaEnabled)};}
function role(v:unknown):AdminRoleRecord{const r=rec(v);const name=str(r.name,r.roleName,r.key)??'';return{id:id(r.id,r.roleId,name),key:str(r.key,r.code,name)??name,name,description:str(r.description),system:bool(r.system,r.isSystem,r.systemRole)??false,permissions:normalizePermissions(r.permissions),usersCount:num(r.usersCount,r.userCount,r.membersCount)??0,createdAt:iso(r.createdAt,r.creationTime),updatedAt:iso(r.updatedAt,r.lastModificationTime,r.createdAt,r.creationTime),systemRole:undefined};}

export async function getRoles(signal?:AbortSignal){const p=unwrap(await apiClient.get<unknown>('/api/dashboard/roles',signal));const r=rec(p);return arr(r.items??r.roles??p).map(role);}
export async function getRole(roleId:string,signal?:AbortSignal){return role(unwrap(await apiClient.get<unknown>(`/api/dashboard/roles/${encodeURIComponent(roleId)}`,signal)));}
export async function getPermissionDefinitions(signal?:AbortSignal):Promise<PermissionDefinition[]>{const p=unwrap(await apiClient.get<unknown>('/api/dashboard/permissions',signal));const r=rec(p);const raw=arr(r.items??r.permissions??p);if(!raw.length)return permissionDefinitions;const byKey=new Map(permissionDefinitions.map(x=>[x.key,x]));return raw.map(x=>{if(typeof x==='string'){return byKey.get(x as Permission)??{key:x as Permission,label:x,description:x,module:'ADMINISTRATION' as const};}const q=rec(x);const key=str(q.key,q.name,q.code) as Permission|undefined;const fallback=key?byKey.get(key):undefined;return{key:key??('settings.read' as Permission),label:str(q.label,q.displayName,q.name)??fallback?.label??key??'',description:str(q.description)??fallback?.description??'',module:(str(q.module) as PermissionDefinition['module'])??fallback?.module??'ADMINISTRATION',sensitive:bool(q.sensitive,q.isSensitive)??fallback?.sensitive};});}
export async function getAdminUsers(filters:AdminFilters,signal?:AbortSignal):Promise<AdminListResult>{const pageSize=Math.max(200,filters.pageSize);const p=unwrap(await apiClient.get<unknown>(`/api/dashboard/admin-users${qs({search:filters.search,page:1,pageSize})}`,signal));const r=rec(p);let items=arr(r.items??r.users??r.adminUsers??p).map(admin);if(filters.status)items=items.filter(x=>x.status===filters.status);if(filters.roleId)items=items.filter(x=>x.roles.some(y=>y.id===filters.roleId||y.key===filters.roleId));if(filters.lastLogin==='NEVER')items=items.filter(x=>!x.lastLoginAt);if(filters.lastLogin==='RECENT_30_DAYS'){const cutoff=Date.now()-30*86400000;items=items.filter(x=>x.lastLoginAt&&new Date(x.lastLoginAt).getTime()>=cutoff);}const total=items.length;const start=(filters.page-1)*filters.pageSize;return{items:items.slice(start,start+filters.pageSize),total,page:filters.page,pageSize:filters.pageSize,pageCount:Math.max(1,Math.ceil(total/filters.pageSize))};}
export async function getAdminUser(adminId:string,signal?:AbortSignal){return admin(unwrap(await apiClient.get<unknown>(`/api/dashboard/admin-users/${encodeURIComponent(adminId)}`,signal)));}
async function roleNamesFromIds(ids:string[]){const roles=await getRoles();return ids.map(roleId=>roles.find(r=>r.id===roleId)?.name??roleId);}
export async function inviteAdmin(input:InviteAdminInput){const names=await roleNamesFromIds(input.roleIds);const p=await apiClient.post<unknown>('/api/dashboard/admin-users/invitations',{email:input.email,roleName:names[0]??null});if(p===undefined)return undefined;const a=admin(unwrap(p));if(a.id&&names.length>1)await apiClient.patch(`/api/dashboard/admin-users/${encodeURIComponent(a.id)}/roles`,{roles:names});return a;}
export const suspendAdmin=(adminId:string,reason:string)=>apiClient.post(`/api/dashboard/admin-users/${encodeURIComponent(adminId)}/suspend`,{reason});
export const reactivateAdmin=(adminId:string)=>apiClient.post(`/api/dashboard/admin-users/${encodeURIComponent(adminId)}/reactivate`);
export async function updateAdminRoles(adminId:string,input:{roleIds:string[]}){const names=await roleNamesFromIds(input.roleIds);return apiClient.patch(`/api/dashboard/admin-users/${encodeURIComponent(adminId)}/roles`,{roles:names});}
export const createRole=(input:CreateRoleInput)=>apiClient.post('/api/dashboard/roles',{name:input.name,permissions:input.permissions});
export const updateRole=(roleId:string,input:UpdateRoleInput)=>apiClient.patch(`/api/dashboard/roles/${encodeURIComponent(roleId)}`,{name:input.name,permissions:input.permissions});
export const deleteRole=(roleId:string)=>apiClient.delete(`/api/dashboard/roles/${encodeURIComponent(roleId)}`);

const emptySettings:SystemSettings={lookups:{REPORT_REJECTION_REASONS:[],ADOPTION_REJECTION_REASONS:[],ORGANIZATION_REASONS:[],ORGANIZATION_SERVICES:[],ANIMAL_TYPES:[]},locations:{governorates:[],regions:[]},emergencyContacts:[],media:{maxImages:8,maxImageMb:8,maxVideoMb:40,allowedTypes:['image/jpeg','image/png','image/webp','video/mp4']},targets:{reportReviewMinutes:120,missionAcceptanceMinutes:30,missionArrivalMinutes:90,supportFirstResponseMinutes:60,adoptionReviewHours:72},backup:{automaticEnabled:false,frequency:'DAILY',retentionCount:14,includeAuditLog:true},backupHistory:[],updatedAt:new Date().toISOString(),updatedBy:{id:'SYSTEM',name:'النظام'}};
function lookupItem(v:unknown,i=0):SystemLookupItem{const r=rec(v);return{id:id(r.id,r.lookupId,r.code,`lookup-${i}`),key:str(r.code,r.key)??id(r.id),label:str(r.label,r.name)??'',active:bool(r.isActive,r.active)??true,order:num(r.sortOrder,r.order)??i+1,locked:bool(r.locked,r.isLocked)};}
function mapSettings(v:unknown):SystemSettings{const r=rec(unwrap(v)), media=rec(r.media??r.mediaLimits), targets=rec(r.targets??r.operationalTargets), backup=rec(r.backup??r.backupSettings);const contacts=arr(r.emergencyContacts).map((x,i)=>{const q=rec(x);const role=String(q.role??q.category??'OTHER').toUpperCase();return{id:id(q.id,`contact-${i}`),name:str(q.name)??'',phone:str(q.phone)??'',category:(role==='VETERINARY'||role==='RESCUE'?role:'OTHER') as SystemSettings['emergencyContacts'][number]['category'],governorate:str(q.governorate),active:bool(q.isActive,q.active)??true};});return{...emptySettings,emergencyContacts:contacts,media:{maxImages:num(media.maxImages)??emptySettings.media.maxImages,maxImageMb:num(media.maxImageMb)??emptySettings.media.maxImageMb,maxVideoMb:num(media.maxVideoMb)??emptySettings.media.maxVideoMb,allowedTypes:arr(media.allowedTypes).length?arr(media.allowedTypes).map(String) as SystemSettings['media']['allowedTypes']:emptySettings.media.allowedTypes},targets:{reportReviewMinutes:num(targets.reportReviewMinutes)??emptySettings.targets.reportReviewMinutes,missionAcceptanceMinutes:num(targets.missionAcceptanceMinutes)??emptySettings.targets.missionAcceptanceMinutes,missionArrivalMinutes:num(targets.missionArrivalMinutes)??emptySettings.targets.missionArrivalMinutes,supportFirstResponseMinutes:num(targets.supportFirstResponseMinutes)??emptySettings.targets.supportFirstResponseMinutes,adoptionReviewHours:num(targets.adoptionReviewHours)??emptySettings.targets.adoptionReviewHours},backup:{automaticEnabled:bool(backup.automaticEnabled,backup.enabled)??false,frequency:(str(backup.frequency) as SystemSettings['backup']['frequency'])??'DAILY',retentionCount:num(backup.retentionCount)??14,includeAuditLog:bool(backup.includeAuditLog)??true,lastBackupAt:str(backup.lastBackupAt),lastBackupBy:backup.lastBackupBy?{id:id(rec(backup.lastBackupBy).id),name:str(rec(backup.lastBackupBy).name)??'النظام'}:undefined},updatedAt:str(r.updatedAt,r.lastModificationTime)??new Date().toISOString(),updatedBy:{id:id(rec(r.updatedBy).id,'SYSTEM'),name:str(rec(r.updatedBy).name)??'النظام'}};}
export async function getSystemSettings(signal?:AbortSignal){return mapSettings(await apiClient.get<unknown>('/api/dashboard/settings',signal));}
export const updateOperationalTargets=(next:SystemSettings['targets'])=>apiClient.patch('/api/dashboard/settings/operational-targets',next);
export const updateMediaLimits=(next:SystemSettings['media'])=>apiClient.patch('/api/dashboard/settings/media-limits',next);
export const updateBackupSettings=(next:SystemSettings['backup'])=>apiClient.patch('/api/dashboard/settings/backup',next);
export const createSystemBackup=()=>apiClient.post('/api/dashboard/settings/backups');
export const addEmergencyContact=(input:Omit<SystemSettings['emergencyContacts'][number],'id'>)=>apiClient.post('/api/dashboard/settings/emergency-contacts',{name:input.name,phone:input.phone,email:null,role:input.category,isActive:input.active});
export const updateEmergencyContact=(c:SystemSettings['emergencyContacts'][number])=>apiClient.patch(`/api/dashboard/settings/emergency-contacts/${encodeURIComponent(c.id)}`,{name:c.name,phone:c.phone,email:null,role:c.category,isActive:c.active});
export const deleteEmergencyContact=(contactId:string)=>apiClient.delete(`/api/dashboard/settings/emergency-contacts/${encodeURIComponent(contactId)}`);
export async function getLookupValues(type:LookupType,signal?:AbortSignal){const p=unwrap(await apiClient.get<unknown>(`/api/dashboard/lookups/${encodeURIComponent(type)}`,signal));const r=rec(p);return arr(r.items??r.values??r.lookups??p).map(lookupItem);}
export const updateLookup=(type:LookupType,item:SystemLookupItem)=>apiClient.patch(`/api/dashboard/lookups/${encodeURIComponent(type)}/${encodeURIComponent(item.id)}`,{label:item.label,code:item.key,isActive:item.active,sortOrder:item.order});
export const addLookup=(type:LookupType,label:string)=>apiClient.post(`/api/dashboard/lookups/${encodeURIComponent(type)}`,{label,code:null,isActive:true,sortOrder:0});
