import { useState, type ReactNode } from 'react';
import { Link } from 'react-router';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { ExternalLink, MapPin, UserRound } from 'lucide-react';
import { toast } from 'sonner';
import { Badge, Button, Card, SectionHeader, Textarea } from '@/components/ui';
import { LocationPreview } from '@/components/ui/location-preview';
import { MediaGallery } from '@/components/ui/media-gallery';
import { OperationalTimeline } from '@/components/ui/operational-timeline';
import { PermissionGuard } from '@/features/auth/rbac';
import { creatorTypeLabels, issueTypeLabels } from '../constants';
import { noteSchema } from '../schemas';
import { useAddFeedingPointNote, useStartFeedingPointIssueReview } from '../hooks';
import type { FeedingPointDetails, FeedingPointIssue, FeedingPointRefill } from '../types';
import { formatFeedingPointDate, formatFeedingPointRelative } from '../utils';
import { ConditionBadge, FoodLevelBadge, IssueStatusBadge, RefillStatusBadge } from './feeding-point-badges';
import { RejectIssueDialog, ResolveIssueDialog, ReviewRefillDialog } from './feeding-point-workflow-dialogs';

function Stat({label,value}:{label:string;value:ReactNode}){return <div className="min-w-0"><p className="text-[11px] text-muted-foreground">{label}</p><div className="mt-1 text-[12px] font-medium text-foreground">{value}</div></div>}

export function PointOverviewSection({details}:{details:FeedingPointDetails}){const point=details.point;const pending=details.refills.filter(item=>item.reviewStatus==='PENDING').length;return <Card className="rounded-xl border-border/45 bg-white p-0 shadow-none"><div className="p-4"><SectionHeader title="معلومات نقطة الإطعام" description="راجع الموقع والصور ومقدم الطلب قبل اتخاذ قرار النشر."/><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="مقدم الطلب" value={<span>{point.createdBy.name} <span className="text-muted-foreground">· {creatorTypeLabels[point.createdBy.type]}</span></span>}/><Stat label="آخر تعبئة مؤكدة" value={point.lastVerifiedRefillAt?formatFeedingPointRelative(point.lastVerifiedRefillAt):'لا توجد بعد'}/><Stat label="تعبئات تنتظر التحقق" value={pending}/><Stat label="حالة الموقع" value={<ConditionBadge condition={point.condition}/>}/></div>{point.description&&<p className="mt-4 border-t border-border/35 pt-3 text-[12px] leading-6 text-muted-foreground">{point.description}</p>}{point.status==='REJECTED'&&point.rejectionReason&&<div className="mt-3 rounded-lg border border-critical/15 bg-critical/[0.04] p-3 text-[12px]"><strong className="text-critical">سبب الرفض:</strong> {point.rejectionReason}</div>}{point.status==='INACTIVE'&&point.inactiveReason&&<div className="mt-3 rounded-lg bg-muted/40 p-3 text-[12px]"><strong>سبب التعطيل:</strong> {point.inactiveReason}</div>}</div><div className="grid border-t border-border/35 lg:grid-cols-2"><div className="p-4 lg:border-e lg:border-border/35"><SectionHeader title="الموقع"/><div className="mt-3"><LocationPreview title={point.name??point.id} address={`${point.location.governorate}${point.location.city?` — ${point.location.city}`:''} · ${point.location.address}`} latitude={point.location.latitude} longitude={point.location.longitude} mapHref={`/map?entityType=FEEDING_POINT&entityId=${point.id}`}/></div></div><div className="p-4"><SectionHeader title="صور إثبات وجود النقطة" description={`${point.media.length} ملفات مرفقة مع طلب الإضافة`}/><div className="mt-3"><MediaGallery items={point.media.map(item=>({id:item.id,type:item.type,url:item.url,thumbnailUrl:item.thumbnailUrl,alt:item.caption??`صورة نقطة الإطعام ${point.id}`}))}/></div></div></div>{point.reviewMetadata?.distanceMeters!==undefined&&<div className="border-t border-border/35 p-4"><div className="rounded-lg border border-pending/20 bg-pending/[0.06] p-3 text-[12px]"><strong>تنبيه:</strong> توجد نقطة أخرى ({point.reviewMetadata.nearbyPointId}) على بعد {point.reviewMetadata.distanceMeters} مترًا تقريبًا. راجع الموقع قبل الموافقة.</div></div>}</Card>}

function RefillRow({pointId,refill}:{pointId:string;refill:FeedingPointRefill}){const[open,setOpen]=useState(false);return <div className="rounded-lg border border-border/40 px-3 py-2.5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-[12px] font-semibold">{refill.submittedBy.name}</p><Badge tone="neutral">{creatorTypeLabels[refill.submittedBy.type]}</Badge><RefillStatusBadge status={refill.reviewStatus}/></div><p className="mt-1 text-[11px] text-muted-foreground">أبلغ عن التعبئة {formatFeedingPointRelative(refill.occurredAt)}</p>{refill.note&&<p className="mt-1.5 text-[12px] text-muted-foreground">{refill.note}</p>}{refill.rejectionReason&&<p className="mt-1.5 text-[11px] text-critical">سبب الرفض: {refill.rejectionReason}</p>}</div>{refill.reviewStatus==='PENDING'&&<PermissionGuard permission="feeding_points.refill.review"><Button size="sm" variant="secondary" onClick={()=>setOpen(true)}>مراجعة</Button></PermissionGuard>}</div>{refill.media.length>0&&<div className="mt-2 max-w-52"><MediaGallery items={refill.media.map(item=>({id:item.id,type:item.type,url:item.url,thumbnailUrl:item.thumbnailUrl,alt:'صورة إعادة تعبئة نقطة الإطعام'}))}/></div>}<ReviewRefillDialog pointId={pointId} refillId={refill.id} open={open} onOpenChange={setOpen}/></div>}
export function RefillsSection({details}:{details:FeedingPointDetails}){return <Card className="rounded-xl border-border/45 bg-white shadow-none"><SectionHeader title="إعادة التعبئة" description="أي مستخدم أو جمعية يمكنه الإبلاغ عن تعبئة النقطة. يظهر البلاغ فورًا ويؤكد الأدمن صحته لاحقًا."/><div className="mt-4 space-y-2.5">{details.refills.length?details.refills.map(refill=><RefillRow key={refill.id} pointId={details.point.id} refill={refill}/>):<p className="text-[12px] text-muted-foreground">لا توجد عمليات تعبئة مسجلة لهذه النقطة بعد.</p>}</div></Card>}

export function SubmitterCard({details}:{details:FeedingPointDetails}){const creator=details.point.createdBy;return <Card className="rounded-xl border-border/45 bg-white shadow-none"><SectionHeader title="مقدم طلب النقطة"/><div className="mt-4 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-muted/60 text-muted-foreground">{creator.type==='USER'?<UserRound className="size-4"/>:<MapPin className="size-4"/>}</span><div className="min-w-0"><p className="truncate text-[12px] font-semibold">{creator.name}</p><p className="text-[11px] text-muted-foreground">{creatorTypeLabels[creator.type]}</p></div></div>{creator.type==='USER'?<Link to={`/users/${creator.id}`} className="mt-3 inline-flex items-center text-[12px] font-medium text-primary">فتح ملف المستخدم <ExternalLink className="ms-1 size-3.5"/></Link>:<Link to={`/organizations/${creator.id}`} className="mt-3 inline-flex items-center text-[12px] font-medium text-primary">فتح ملف الجمعية <ExternalLink className="ms-1 size-3.5"/></Link>}</Card>}

export function PointMetaCard({details}:{details:FeedingPointDetails}){const point=details.point;return <Card className="rounded-xl border-border/45 bg-white shadow-none"><SectionHeader title="بيانات السجل"/><dl className="mt-4 space-y-3"><div><dt className="text-[11px] text-muted-foreground">رقم النقطة</dt><dd dir="ltr" className="mt-1 font-mono text-[12px] font-semibold">{point.id}</dd></div><div><dt className="text-[11px] text-muted-foreground">تاريخ تقديم الطلب</dt><dd className="mt-1 text-[12px] font-medium">{formatFeedingPointDate(point.createdAt)}</dd></div><div><dt className="text-[11px] text-muted-foreground">آخر نشاط</dt><dd className="mt-1 text-[12px] font-medium">{formatFeedingPointRelative(point.latestRefillReportAt??point.updatedAt)}</dd></div><div className="grid grid-cols-2 gap-3 border-t border-border/35 pt-3"><Stat label="الطعام بعد آخر تحقق" value={<FoodLevelBadge level={point.foodLevel}/>}/><Stat label="المياه" value={point.waterAvailable===true?'متوفرة':point.waterAvailable===false?'غير متوفرة':'غير معروف'}/></div></dl></Card>}

export function TimelineCard({details}:{details:FeedingPointDetails}){return <Card className="rounded-xl border-border/45 bg-white shadow-none"><SectionHeader title="السجل الإداري" description="قرارات النشر، التحقق من التعبئات والتغييرات الإدارية."/><div className="mt-4"><OperationalTimeline items={details.timeline.map(event=>({id:event.id,title:event.action,actor:event.actor,timestampLabel:formatFeedingPointDate(event.timestamp),details:event.details,tone:event.tone}))}/></div></Card>}

function IssueRow({pointId,issue}:{pointId:string;issue:FeedingPointIssue}){const[resolveOpen,setResolveOpen]=useState(false),[rejectOpen,setRejectOpen]=useState(false);const start=useStartFeedingPointIssueReview(pointId);return <div className="rounded-lg border border-border/40 p-3"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="text-[12px] font-semibold">{issueTypeLabels[issue.type]}</p><IssueStatusBadge status={issue.status}/></div><p className="mt-1 text-[11px] text-muted-foreground">{issue.submittedBy.name} · {formatFeedingPointRelative(issue.createdAt)}</p>{issue.description&&<p className="mt-1.5 text-[12px]">{issue.description}</p>}</div>{['OPEN','UNDER_REVIEW'].includes(issue.status)&&<PermissionGuard permission="feeding_points.issues.review"><div className="flex gap-2">{issue.status==='OPEN'&&<Button size="sm" variant="ghost" onClick={()=>start.mutate(issue.id,{onSuccess:()=>toast.success('بدأت مراجعة المشكلة')})}>بدء المراجعة</Button>}<Button size="sm" variant="secondary" onClick={()=>setResolveOpen(true)}>حل</Button><Button size="sm" variant="ghost" className="text-critical" onClick={()=>setRejectOpen(true)}>رفض</Button></div></PermissionGuard>}</div><ResolveIssueDialog pointId={pointId} issueId={issue.id} open={resolveOpen} onOpenChange={setResolveOpen}/><RejectIssueDialog pointId={pointId} issueId={issue.id} open={rejectOpen} onOpenChange={setRejectOpen}/></div>}
export function IssuesCard({details}:{details:FeedingPointDetails}){return <Card className="rounded-xl border-border/45 bg-white shadow-none"><SectionHeader title="مشكلات النقطة" description="ملاحظات منفصلة عن إعادة التعبئة مثل الضرر أو النظافة أو فقدان النقطة."/><div className="mt-4 space-y-2.5">{details.issues.length?details.issues.map(issue=><IssueRow key={issue.id} pointId={details.point.id} issue={issue}/>):<p className="text-[12px] text-muted-foreground">لا توجد مشكلات مسجلة.</p>}</div></Card>}

export function NotesCard({details}:{details:FeedingPointDetails}){const mutation=useAddFeedingPointNote(details.point.id);const{register,handleSubmit,reset,formState:{errors}}=useForm<{note:string}>({resolver:zodResolver(noteSchema),defaultValues:{note:''}});return <Card className="rounded-xl border-border/45 bg-white shadow-none"><SectionHeader title="ملاحظات داخلية"/><form className="mt-4" onSubmit={event=>{event.preventDefault();void handleSubmit(value=>mutation.mutate(value.note,{onSuccess:()=>{toast.success('تمت إضافة الملاحظة');reset();}}))();}}><Textarea {...register('note')} placeholder="ملاحظة لفريق الإدارة…"/>{errors.note&&<p className="mt-1 text-[11px] text-critical">{errors.note.message}</p>}<Button size="sm" className="mt-2" disabled={mutation.isPending}>إضافة</Button></form>{details.notes.length>0&&<div className="mt-4 space-y-2">{details.notes.map(note=><div key={note.id} className="rounded-lg border border-border/35 p-2.5"><div className="flex justify-between gap-2"><p className="text-[12px] font-medium">{note.adminName}</p><span className="text-[11px] text-muted-foreground">{formatFeedingPointRelative(note.createdAt)}</span></div><p className="mt-1 text-[12px] text-muted-foreground">{note.note}</p></div>)}</div>}</Card>}
