import { useMemo,type ReactNode } from 'react';
import type { ColumnDef } from '@tanstack/react-table';
import { ExternalLink,FileText,HeartHandshake,MoreHorizontal } from 'lucide-react';
import { useNavigate } from 'react-router';
import { Avatar,DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger,IconButton } from '@/components/ui';
import { DataTable,type DataTableQueryState } from '@/components/ui/data-table';
import type { User,UserFilters } from '../types';
import { formatUserDate,formatUserRelative } from '../utils';
import { UserAccountStatusBadge,UserVerificationBadge } from './user-badges';
export function UsersTable({items,total,pageCount,filters,loading,error,onRetry,onQueryChange,emptyState}:{items:User[];total:number;pageCount:number;filters:UserFilters;loading:boolean;error?:string;onRetry:()=>void;onQueryChange:(state:DataTableQueryState)=>void;emptyState:ReactNode}){const nav=useNavigate();const columns=useMemo<Array<ColumnDef<User,unknown>>>(()=>[{id:'fullName',header:'المستخدم',cell:({row})=><div className="flex items-center gap-3"><Avatar name={row.original.fullName} src={row.original.avatarUrl}/><div><p className="font-medium">{row.original.fullName}</p><p className="text-xs text-muted-foreground" dir="ltr">{row.original.id}</p></div></div>},{id:'accountStatus',header:'الحالة',cell:({row})=><UserAccountStatusBadge status={row.original.accountStatus}/>},{id:'verification',header:'التوثيق',enableSorting:false,cell:({row})=><UserVerificationBadge status={row.original.verificationStatus}/>},{id:'governorate',header:'المحافظة',enableSorting:false,cell:({row})=>row.original.governorate??'—'},{id:'reports',header:'البلاغات',enableSorting:false,cell:({row})=>(row.original.statistics?.reportsCount??0).toLocaleString('ar-SA-u-nu-latn')},{id:'adoptions',header:'طلبات التبني',enableSorting:false,cell:({row})=>(row.original.statistics?.adoptionRequestsCount??0).toLocaleString('ar-SA-u-nu-latn')},{id:'lastActiveAt',header:'آخر نشاط',cell:({row})=>row.original.lastActiveAt?formatUserRelative(row.original.lastActiveAt):'غير متاح'},{id:'createdAt',header:'تاريخ التسجيل',cell:({row})=>formatUserDate(row.original.createdAt)}],[]);return <DataTable data={items} columns={columns} getRowId={u=>u.id} enableSearch={false} manualPagination manualSorting manualFiltering pageCount={pageCount} totalCount={total} loading={loading} error={error} onRetry={onRetry} state={{pageIndex:filters.page-1,pageSize:filters.pageSize,search:filters.search,sorting:filters.sortBy?[{id:filters.sortBy,desc:filters.sortDirection!=='asc'}]:[]}} onStateChange={onQueryChange} onRowClick={u=>nav(`/users/${u.id}`)} rowAriaLabel={u=>`فتح حساب ${u.fullName}`} rowActions={u=><DropdownMenu><DropdownMenuTrigger asChild><IconButton label={`إجراءات ${u.fullName}`}><MoreHorizontal className="size-4"/></IconButton></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onSelect={()=>nav(`/users/${u.id}`)}><ExternalLink className="size-4"/>عرض الحساب</DropdownMenuItem><DropdownMenuItem onSelect={()=>nav(`/reports?userId=${encodeURIComponent(u.id)}`)}><FileText className="size-4"/>فتح البلاغات</DropdownMenuItem><DropdownMenuItem onSelect={()=>nav(`/adoption-requests?userId=${encodeURIComponent(u.id)}`)}><HeartHandshake className="size-4"/>فتح طلبات التبني</DropdownMenuItem></DropdownMenuContent></DropdownMenu>} emptyState={emptyState}/>;}
