import type{AdminSession}from'@/features/auth/session';
import{getUserById}from'@/features/users/services/users.mock';
import{getOrganizationById}from'@/features/organizations/services/organizations.mock';
import{mockDelay}from'@/services/mock/delay';
import{recordAdminAuditEvent}from'@/features/audit-log/services/audit-log.mock';
import{allowedSupportTransitions,supportCannedResponses}from'../constants';
import type{AssignTicketInput,ChangePriorityInput,EscalateTicketInput,ReplyTicketInput,ReopenTicketInput,ResolveTicketInput,SupportCannedResponse,SupportFilters,SupportInternalNote,SupportListResult,SupportMessage,SupportRequester,SupportRequesterType,SupportSummary,SupportTicket,SupportTicketCategory,SupportTicketDetails,SupportTicketPriority,SupportTicketStatus,SupportTimelineEvent,UserSupportSummary}from'../types';
const now=Date.now(),minsAgo=(n:number)=>new Date(now-n*60000).toISOString(),hoursAgo=(n:number)=>minsAgo(n*60),daysAgo=(n:number)=>hoursAgo(n*24),clone=<T>(v:T):T=>structuredClone(v);
type Seed={id:string;subject:string;category:SupportTicketCategory;status:SupportTicketStatus;priority:SupportTicketPriority;requesterType:SupportRequesterType;requesterId:string;relatedResource?:SupportTicket['relatedResource'];assignee?:SupportTicket['assignee'];createdAt:string;updatedAt:string;firstResponseAt?:string;resolvedAt?:string;closedAt?:string;resolutionSummary?:string;escalation?:SupportTicket['escalation']};
const seeds:Seed[]=[
{id:'SUP-2026-0142',subject:'لم أستطع تعديل رقم الهاتف',category:'ACCOUNT',status:'OPEN',priority:'NORMAL',requesterType:'USER',requesterId:'USR-1001',assignee:{id:'ADM-SUP-002',name:'رنا المصري',role:'وكيل الدعم'},createdAt:hoursAgo(5),updatedAt:minsAgo(38),firstResponseAt:hoursAgo(4.5)},
{id:'SUP-2026-0143',subject:'بلاغ إنقاذ لم يتم تحديثه منذ ساعات',category:'REPORT',status:'OPEN',priority:'URGENT',requesterType:'USER',requesterId:'USR-1003',relatedResource:{type:'REPORT',id:'RQ-2026-00481'},createdAt:hoursAgo(3),updatedAt:minsAgo(16)},
{id:'SUP-2026-0144',subject:'مشكلة في ظهور إعلان الجمعية',category:'ADVERTISEMENT',status:'WAITING_FOR_INTERNAL',priority:'HIGH',requesterType:'ORGANIZATION',requesterId:'ORG-001',relatedResource:{type:'ADVERTISEMENT',id:'ADVT-2026-0025'},assignee:{id:'ADM-SUP-003',name:'ليان حمود',role:'وكيل الدعم'},createdAt:daysAgo(1.2),updatedAt:hoursAgo(2),firstResponseAt:daysAgo(1.1),escalation:{escalated:true,escalatedAt:hoursAgo(7),reason:'تحتاج مراجعة حالة الحملة من فريق المحتوى.',targetTeam:'CONTENT'}},
{id:'SUP-2026-0145',subject:'استفسار عن حالة تبرع',category:'DONATION',status:'WAITING_FOR_USER',priority:'NORMAL',requesterType:'USER',requesterId:'USR-1107',relatedResource:{type:'DONATION',id:'DN-2026-00821'},assignee:{id:'ADM-SUP-002',name:'رنا المصري',role:'وكيل الدعم'},createdAt:daysAgo(2),updatedAt:hoursAgo(9),firstResponseAt:daysAgo(1.8)},
{id:'SUP-2026-0146',subject:'تعذر إكمال طلب التبني',category:'ADOPTION',status:'NEW',priority:'HIGH',requesterType:'USER',requesterId:'USR-1002',relatedResource:{type:'ADOPTION_REQUEST',id:'AD-2026-0105'},createdAt:minsAgo(44),updatedAt:minsAgo(44)},
{id:'SUP-2026-0148',subject:'اقتراح لتحسين تجربة الخريطة',category:'TECHNICAL',status:'RESOLVED',priority:'LOW',requesterType:'USER',requesterId:'USR-1004',assignee:{id:'ADM-SUP-004',name:'سامر درويش',role:'مشرف الدعم'},createdAt:daysAgo(3),updatedAt:hoursAgo(1),firstResponseAt:daysAgo(2.9),resolvedAt:hoursAgo(1),resolutionSummary:'تم توثيق الملاحظة وإحالتها إلى فريق المنتج.'},
{id:'SUP-2026-0149',subject:'شكوى بخصوص تأخر متابعة جمعية',category:'COMPLAINT',status:'OPEN',priority:'HIGH',requesterType:'USER',requesterId:'USR-1005',relatedResource:{type:'ORGANIZATION',id:'ORG-003'},assignee:{id:'ADM-SUP-003',name:'ليان حمود',role:'وكيل الدعم'},createdAt:daysAgo(1),updatedAt:minsAgo(55),firstResponseAt:hoursAgo(20)},
{id:'SUP-2026-0150',subject:'مشكلة سابقة في تسجيل الدخول',category:'ACCOUNT',status:'CLOSED',priority:'NORMAL',requesterType:'USER',requesterId:'USR-1160',assignee:{id:'ADM-SUP-004',name:'سامر درويش',role:'مشرف الدعم'},createdAt:daysAgo(12),updatedAt:daysAgo(7),firstResponseAt:daysAgo(11.8),resolvedAt:daysAgo(8),closedAt:daysAgo(7),resolutionSummary:'تمت استعادة الوصول والتحقق من عمل الحساب.'},
{id:'SUP-2026-0152',subject:'سؤال عن حالة حيوان بعد التبني',category:'ADOPTION',status:'WAITING_FOR_USER',priority:'LOW',requesterType:'USER',requesterId:'USR-1120',relatedResource:{type:'ADOPTION_REQUEST',id:'AD-2026-0108'},assignee:{id:'ADM-SUP-003',name:'ليان حمود',role:'وكيل الدعم'},createdAt:daysAgo(4),updatedAt:daysAgo(1),firstResponseAt:daysAgo(3.8)},
{id:'SUP-2026-0153',subject:'استفسار تشغيلي عن ملف الجمعية',category:'ORGANIZATION',status:'RESOLVED',priority:'NORMAL',requesterType:'ORGANIZATION',requesterId:'ORG-002',relatedResource:{type:'ORGANIZATION',id:'ORG-002'},assignee:{id:'ADM-SUP-004',name:'سامر درويش',role:'مشرف الدعم'},createdAt:daysAgo(2),updatedAt:minsAgo(20),firstResponseAt:daysAgo(1.9),resolvedAt:minsAgo(20),resolutionSummary:'تم توضيح خطوات تحديث الملف وتأكيد وصول البيانات.'},
];
const messageMap=new Map<string,SupportMessage[]>(),noteMap=new Map<string,SupportInternalNote[]>(),timelineMap=new Map<string,SupportTimelineEvent[]>();
for(const s of seeds){messageMap.set(s.id,[{id:`MSG-${s.id}-1`,ticketId:s.id,authorType:'REQUESTER',author:{id:s.requesterId,name:'مقدم الطلب'},body:s.subject==='لم أستطع تعديل رقم الهاتف'?'أحاول تعديل رقم الهاتف من الحساب لكن لا يتم حفظ الرقم الجديد.':`مرحبًا، أحتاج مساعدة بخصوص: ${s.subject}.`,createdAt:s.createdAt},...(s.firstResponseAt?[{id:`MSG-${s.id}-2`,ticketId:s.id,authorType:'ADMIN' as const,author:{id:s.assignee?.id??'ADM-SUP',name:s.assignee?.name??'فريق الدعم'},body:'تم استلام طلبك ونحن نتابع التفاصيل. سنشاركك التحديث عند توفره.',createdAt:s.firstResponseAt}]:[])]);timelineMap.set(s.id,[{id:`TL-${s.id}-1`,label:'تم إنشاء التذكرة',createdAt:s.createdAt},...(s.assignee?[{id:`TL-${s.id}-2`,label:`تم إسناد التذكرة إلى ${s.assignee.name}`,actorName:s.assignee.name,createdAt:s.firstResponseAt??s.updatedAt}]:[]),...(s.escalation?.escalated?[{id:`TL-${s.id}-3`,label:'تم تصعيد التذكرة',details:s.escalation.reason,createdAt:s.escalation.escalatedAt??s.updatedAt}]:[]),...(s.resolvedAt?[{id:`TL-${s.id}-4`,label:'تم حل التذكرة',details:s.resolutionSummary,createdAt:s.resolvedAt}]:[]),...(s.closedAt?[{id:`TL-${s.id}-5`,label:'تم إغلاق التذكرة',createdAt:s.closedAt}]:[])]);}
async function requester(type:SupportRequesterType,id:string):Promise<SupportRequester>{if(type==='USER'){const d=await getUserById(id);if(d)return{id:d.user.id,name:d.user.fullName,email:d.user.email,phone:d.user.phone,type};}if(type==='ORGANIZATION'){const d=await getOrganizationById(id);if(d)return{id:d.organization.id,name:d.organization.name,email:d.organization.email,phone:d.organization.phone,type};}return{id,name:id,type};}
async function resolve(s:Seed):Promise<SupportTicket>{const r=await requester(s.requesterType,s.requesterId);return{...s,requester:r,messagesCount:messageMap.get(s.id)?.length??0};}
function seed(id:string){const s=seeds.find(x=>x.id===id);if(!s)throw new Error('TICKET_NOT_FOUND');return s;}
function event(id:string,label:string,actor?:AdminSession,details?:string){timelineMap.set(id,[...(timelineMap.get(id)??[]),{id:`TL-${id}-${Date.now()}`,label,actorName:actor?.name,details,createdAt:new Date().toISOString()}]);}
export async function getSupportTickets(f:SupportFilters):Promise<SupportListResult>{await mockDelay(70);let rows=await Promise.all(seeds.map(resolve));const n=f.search.trim().toLocaleLowerCase('ar');rows=rows.filter(t=>{const hay=`${t.id} ${t.subject} ${t.requester.name} ${t.relatedResource?.id??''}`.toLocaleLowerCase('ar');if(n&&!hay.includes(n))return false;if(f.status&&t.status!==f.status)return false;if(f.priority&&t.priority!==f.priority)return false;if(f.category&&t.category!==f.category)return false;if(f.requesterType&&t.requester.type!==f.requesterType)return false;if(f.assignee==='me'&&t.assignee?.id!=='mock-admin-001')return false;if(f.assignee&&f.assignee!=='me'&&t.assignee?.id!==f.assignee)return false;if(f.unassigned===true&&t.assignee)return false;if(f.userId&&(t.requester.type!=='USER'||t.requester.id!==f.userId))return false;if(f.organizationId&&(t.requester.type!=='ORGANIZATION'||t.requester.id!==f.organizationId))return false;if(f.waiting==='USER'&&t.status!=='WAITING_FOR_USER')return false;if(f.waiting==='INTERNAL'&&t.status!=='WAITING_FOR_INTERNAL')return false;if(f.dateFrom&&new Date(t.createdAt)<new Date(`${f.dateFrom}T00:00:00`))return false;if(f.dateTo&&new Date(t.createdAt)>new Date(`${f.dateTo}T23:59:59`))return false;return true;});const rank:Record<SupportTicketPriority,number>={LOW:1,NORMAL:2,HIGH:3,URGENT:4};rows.sort((a,b)=>{let d=0;if(f.sortBy==='priority')d=rank[a.priority]-rank[b.priority];else if(f.sortBy==='status')d=a.status.localeCompare(b.status);else d=new Date(a[f.sortBy==='createdAt'?'createdAt':'updatedAt']).getTime()-new Date(b[f.sortBy==='createdAt'?'createdAt':'updatedAt']).getTime();return(f.sortDirection==='asc'?1:-1)*d});const total=rows.length,pageCount=Math.max(1,Math.ceil(total/f.pageSize)),page=Math.min(f.page,pageCount);return{items:clone(rows.slice((page-1)*f.pageSize,page*f.pageSize)),total,page,pageSize:f.pageSize,pageCount};}
export async function getSupportTicket(id:string):Promise<SupportTicketDetails|null>{await mockDelay(70);const s=seeds.find(x=>x.id===id);if(!s)return null;return clone({ticket:await resolve(s),messages:messageMap.get(id)??[],notes:noteMap.get(id)??[],timeline:timelineMap.get(id)??[]});}
export async function getSupportSummary():Promise<SupportSummary>{const rows=await Promise.all(seeds.map(resolve));const today=new Date().toDateString();return{newCount:rows.filter(x=>x.status==='NEW').length,openCount:rows.filter(x=>['OPEN','WAITING_FOR_USER','WAITING_FOR_INTERNAL'].includes(x.status)).length,urgentCount:rows.filter(x=>x.priority==='URGENT'&&!['RESOLVED','CLOSED'].includes(x.status)).length,waitingForUser:rows.filter(x=>x.status==='WAITING_FOR_USER').length,unassigned:rows.filter(x=>!x.assignee&&!['RESOLVED','CLOSED'].includes(x.status)).length,resolvedToday:rows.filter(x=>x.resolvedAt&&new Date(x.resolvedAt).toDateString()===today).length};}
export async function getUserSupportSummary(userId:string):Promise<UserSupportSummary>{const rows=(await Promise.all(seeds.filter(x=>x.requesterType==='USER'&&x.requesterId===userId).map(resolve))).sort((a,b)=>new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime());return{total:rows.length,open:rows.filter(x=>!['RESOLVED','CLOSED'].includes(x.status)).length,recent:rows.slice(0,3).map(x=>({id:x.id,subject:x.subject,status:x.status,updatedAt:x.updatedAt}))};}
export async function assignSupportTicket(id:string,input:AssignTicketInput,actor:AdminSession){await mockDelay(60);const s=seed(id);s.assignee={id:input.assigneeId,name:input.assigneeName,role:input.assigneeRole};if(s.status==='NEW')s.status='OPEN';s.updatedAt=new Date().toISOString();event(id,`تم إسناد التذكرة إلى ${input.assigneeName}`,actor);recordAdminAuditEvent(actor,{action:'SUPPORT_TICKET_ASSIGNED',resource:{type:'SUPPORT_TICKET',id,label:s.subject},newValue:{assignee:input.assigneeName,status:s.status},metadata:{source:'مركز الدعم'}});return resolve(s);}
export async function changeSupportPriority(id:string,input:ChangePriorityInput,actor:AdminSession){await mockDelay(50);const s=seed(id);s.priority=input.priority;s.updatedAt=new Date().toISOString();event(id,'تم تغيير أولوية التذكرة',actor,input.reason);return resolve(s);}
export async function changeSupportStatus(id:string,status:SupportTicketStatus,actor:AdminSession){await mockDelay(50);const s=seed(id);if(!allowedSupportTransitions[s.status].includes(status))throw new Error('INVALID_STATUS_TRANSITION');s.status=status;s.updatedAt=new Date().toISOString();event(id,'تم تغيير حالة التذكرة',actor,`الحالة الجديدة: ${status}`);return resolve(s);}
export async function replyToSupportTicket(id:string,input:ReplyTicketInput,actor:AdminSession){await mockDelay(70);const s=seed(id);if(['RESOLVED','CLOSED'].includes(s.status))throw new Error('TICKET_NOT_OPEN');const createdAt=new Date().toISOString();messageMap.set(id,[...(messageMap.get(id)??[]),{id:`MSG-${id}-${Date.now()}`,ticketId:id,authorType:'ADMIN',author:{id:actor.id,name:actor.name},body:input.body,createdAt}]);if(!s.firstResponseAt)s.firstResponseAt=createdAt;s.status=input.waitForUser?'WAITING_FOR_USER':'OPEN';s.updatedAt=createdAt;event(id,input.waitForUser?'أرسل فريق الدعم ردًا وأصبحت التذكرة بانتظار المستخدم':'أرسل فريق الدعم ردًا',actor);return getSupportTicket(id);}
export async function addSupportInternalNote(id:string,body:string,actor:AdminSession){await mockDelay(45);seed(id);noteMap.set(id,[...(noteMap.get(id)??[]),{id:`NOTE-${id}-${Date.now()}`,ticketId:id,author:{id:actor.id,name:actor.name,role:actor.roleLabel},body,createdAt:new Date().toISOString()}]);event(id,'تمت إضافة ملاحظة داخلية',actor);return getSupportTicket(id);}
export async function escalateSupportTicket(id:string,input:EscalateTicketInput,actor:AdminSession){await mockDelay(55);const s=seed(id);s.escalation={escalated:true,escalatedAt:new Date().toISOString(),reason:input.reason,targetTeam:input.targetTeam};s.status='WAITING_FOR_INTERNAL';s.updatedAt=new Date().toISOString();event(id,'تم تصعيد التذكرة إلى فريق داخلي',actor,input.reason);return resolve(s);}
export async function resolveSupportTicket(id:string,input:ResolveTicketInput,actor:AdminSession){await mockDelay(55);const s=seed(id);if(['RESOLVED','CLOSED'].includes(s.status))throw new Error('ALREADY_RESOLVED');s.status='RESOLVED';s.resolvedAt=new Date().toISOString();s.resolutionSummary=input.summary;s.updatedAt=s.resolvedAt;event(id,'تم حل التذكرة',actor,input.summary);recordAdminAuditEvent(actor,{action:'SUPPORT_TICKET_RESOLVED',resource:{type:'SUPPORT_TICKET',id,label:s.subject},reason:input.summary,previousValue:{status:'OPEN'},newValue:{status:'RESOLVED'},metadata:{source:'مركز الدعم'}});return resolve(s);}
export async function closeSupportTicket(id:string,actor:AdminSession){await mockDelay(50);const s=seed(id);if(s.status!=='RESOLVED')throw new Error('MUST_RESOLVE_FIRST');s.status='CLOSED';s.closedAt=new Date().toISOString();s.updatedAt=s.closedAt;event(id,'تم إغلاق التذكرة',actor);return resolve(s);}
export async function reopenSupportTicket(id:string,input:ReopenTicketInput,actor:AdminSession){await mockDelay(55);const s=seed(id);if(!['RESOLVED','CLOSED'].includes(s.status))throw new Error('CANNOT_REOPEN');s.status='OPEN';s.closedAt=undefined;s.resolvedAt=undefined;s.updatedAt=new Date().toISOString();event(id,'تمت إعادة فتح التذكرة',actor,input.reason);recordAdminAuditEvent(actor,{action:'SUPPORT_TICKET_REOPENED',resource:{type:'SUPPORT_TICKET',id,label:s.subject},reason:input.reason,newValue:{status:'OPEN'},metadata:{source:'مركز الدعم'}});return resolve(s);}
export async function getSupportCannedResponses():Promise<SupportCannedResponse[]>{await mockDelay(20);return clone(supportCannedResponses.map(x=>({...x})));}
