import type { AdminSession } from '@/features/auth/session';
import { apiClient } from '@/services/api/client';
import type {
  AssignTicketInput, ChangePriorityInput, EscalateTicketInput, ReplyTicketInput,
  ReopenTicketInput, ResolveTicketInput, SupportCannedResponse, SupportFilters,
  SupportListResult, SupportSummary, SupportTicket, SupportTicketDetails,
  SupportTicketPriority, SupportTicketStatus, UserSupportSummary,
} from '../types';

type R=Record<string,unknown>;
const rec=(v:unknown):R=>v&&typeof v==='object'&&!Array.isArray(v)?v as R:{};
const arr=(v:unknown):unknown[]=>Array.isArray(v)?v:[];
const str=(...v:unknown[]):string|undefined=>v.find(x=>typeof x==='string'&&x.trim()) as string|undefined;
const num=(...v:unknown[]):number|undefined=>{for(const x of v){const n=typeof x==='number'?x:typeof x==='string'?Number(x):NaN;if(Number.isFinite(n))return n;}return undefined;};
const id=(...v:unknown[])=>String(v.find(x=>x!==null&&x!==undefined&&String(x).trim())??'');
const unwrap=(v:unknown):unknown=>{const r=rec(v);return r.data??r.result??r.value??v;};
const iso=(...values:unknown[]):string|undefined=>{const s=str(...values);if(!s)return undefined;const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toISOString();};
const qs=(o:Record<string,unknown>)=>{const p=new URLSearchParams();Object.entries(o).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')p.set(k,String(v));});const s=p.toString();return s?`?${s}`:'';};
const statusMap:Record<string,SupportTicketStatus>={NEW:'NEW',OPEN:'OPEN',WAITING_FOR_USER:'WAITING_FOR_USER',WAITING_USER:'WAITING_FOR_USER',WAITING_FOR_INTERNAL:'WAITING_FOR_INTERNAL',WAITING_INTERNAL:'WAITING_FOR_INTERNAL',RESOLVED:'RESOLVED',CLOSED:'CLOSED'};
const priorityMap:Record<string,SupportTicketPriority>={LOW:'LOW',NORMAL:'NORMAL',MEDIUM:'NORMAL',HIGH:'HIGH',URGENT:'URGENT',CRITICAL:'URGENT'};
const normalizeStatus=(v:unknown)=>statusMap[String(v??'').toUpperCase()]??'NEW';
const normalizePriority=(v:unknown)=>priorityMap[String(v??'').toUpperCase()]??'NORMAL';
function ticket(v:unknown):SupportTicket{const r=rec(v),req=rec(r.requester??r.user??r.organization),ass=rec(r.assignee??r.assignedAdmin),rel=rec(r.relatedResource),esc=rec(r.escalation);return{id:id(r.id,r.ticketId),subject:str(r.subject,r.title)??'',category:(str(r.category)?.toUpperCase() as SupportTicket['category'])??'OTHER',status:normalizeStatus(r.status),priority:normalizePriority(r.priority),requester:{type:(String(r.requesterType??req.type??'USER').toUpperCase()==='ORGANIZATION'?'ORGANIZATION':'USER'),id:id(req.id,req.userId,req.organizationId,r.requesterId),name:str(req.name,req.fullName,r.requesterName)??'—',email:str(req.email),phone:str(req.phone)},assignee:Object.keys(ass).length?{id:id(ass.id,ass.adminId,r.assigneeId),name:str(ass.name,ass.fullName,r.assigneeName)??'—',role:str(ass.role,ass.roleName,r.assigneeRole)??''}:undefined,relatedResource:Object.keys(rel).length?{type:(str(rel.type,r.relatedResourceType)?.toUpperCase() as any),id:id(rel.id,r.relatedResourceId)}:undefined,messagesCount:num(r.messagesCount,r.messageCount)??0,createdAt:iso(r.createdAt,r.creationTime)??new Date().toISOString(),updatedAt:iso(r.updatedAt,r.lastModificationTime,r.createdAt)??new Date().toISOString(),firstResponseAt:iso(r.firstResponseAt),resolvedAt:iso(r.resolvedAt),closedAt:iso(r.closedAt),resolutionSummary:str(r.resolutionSummary,r.resolution),escalation:Object.keys(esc).length?{escalated:Boolean(esc.escalated??true),escalatedAt:iso(esc.escalatedAt),reason:str(esc.reason),targetTeam:str(esc.targetTeam)?.toUpperCase() as any}:undefined};}
function details(v:unknown):SupportTicketDetails{const r=rec(v),t=ticket(r.ticket??v);return{ticket:t,messages:arr(r.messages).map((x,i)=>{const q=rec(x),a=rec(q.author);return{id:id(q.id,`msg-${i}`),ticketId:t.id,authorType:String(q.authorType??'REQUESTER').toUpperCase()==='ADMIN'?'ADMIN':'REQUESTER',author:{id:id(a.id,q.authorId),name:str(a.name,q.authorName)??'—'},body:str(q.body,q.message)??'',attachments:arr(q.attachments).map((z,j)=>{const e=rec(z);return{id:id(e.id,`${i}-${j}`),name:str(e.name,e.fileName)??'',type:str(e.type,e.contentType)??'',size:num(e.size)??0,url:str(e.url,e.fileUrl)??''};}),createdAt:iso(q.createdAt,q.creationTime)??new Date().toISOString()};}),notes:arr(r.notes??r.internalNotes).map((x,i)=>{const q=rec(x),a=rec(q.author);return{id:id(q.id,`note-${i}`),ticketId:t.id,author:{id:id(a.id,q.authorId),name:str(a.name,q.authorName)??'—',role:str(a.role,q.authorRole)},body:str(q.body,q.note)??'',createdAt:iso(q.createdAt,q.creationTime)??new Date().toISOString()};}),timeline:arr(r.timeline??r.events).map((x,i)=>{const q=rec(x);return{id:id(q.id,`event-${i}`),label:str(q.label,q.title,q.action)??'تحديث',actorName:str(q.actorName,q.actor),details:str(q.details,q.description),createdAt:iso(q.createdAt,q.timestamp)??new Date().toISOString()};})};}
export async function getSupportTickets(f:SupportFilters,signal?:AbortSignal):Promise<SupportListResult>{const p=unwrap(await apiClient.get<unknown>(`/api/dashboard/support/tickets${qs({search:f.search,status:f.status,priority:f.priority,page:f.page,pageSize:f.pageSize})}`,signal));const r=rec(p),items=arr(r.items??r.tickets??r.data??p).map(ticket),total=num(r.total,r.totalCount)??items.length,page=num(r.page)??f.page,pageSize=num(r.pageSize)??f.pageSize;return{items,total,page,pageSize,pageCount:Math.max(1,num(r.pageCount)??Math.ceil(total/pageSize))};}
export async function getSupportSummary(signal?:AbortSignal):Promise<SupportSummary>{const r=rec(unwrap(await apiClient.get<unknown>('/api/dashboard/support/summary',signal)));return{newCount:num(r.newCount,r.new)??0,openCount:num(r.openCount,r.open)??0,urgentCount:num(r.urgentCount,r.urgent)??0,waitingForUser:num(r.waitingForUser,r.waitingForUserCount)??0,unassigned:num(r.unassigned,r.unassignedCount)??0,resolvedToday:num(r.resolvedToday,r.resolvedTodayCount)??0};}
export async function getSupportTicket(idValue:string,signal?:AbortSignal){const p=unwrap(await apiClient.get<unknown>(`/api/dashboard/support/tickets/${encodeURIComponent(idValue)}`,signal));return p==null?null:details(p);}
export async function getUserSupportSummary(userId:string,signal?:AbortSignal):Promise<UserSupportSummary>{const r=rec(unwrap(await apiClient.get<unknown>(`/api/dashboard/users/${encodeURIComponent(userId)}/support/summary`,signal)));return{total:num(r.total,r.totalCount)??0,open:num(r.open,r.openCount)??0,recent:arr(r.recent??r.items).map(x=>{const q=rec(x);return{id:id(q.id,q.ticketId),subject:str(q.subject,q.title)??'',status:normalizeStatus(q.status),updatedAt:iso(q.updatedAt,q.lastModificationTime)??new Date().toISOString()};})};}
export async function getSupportAssignees(signal?:AbortSignal){const p=unwrap(await apiClient.get<unknown>('/api/dashboard/admin-users?page=1&pageSize=100',signal));const r=rec(p);return arr(r.items??r.users??r.adminUsers??p).map(x=>{const q=rec(x);return{id:id(q.id,q.userId),name:str(q.name,q.fullName,q.email)??id(q.id),role:str(q.roleLabel,q.roleName,q.role)??'',workload:num(q.workload,q.openTicketsCount)??0};}).filter(x=>x.id);}
export async function getSupportCannedResponses(signal?:AbortSignal):Promise<SupportCannedResponse[]>{const p=unwrap(await apiClient.get<unknown>('/api/dashboard/support/canned-responses',signal));const r=rec(p);return arr(r.items??r.responses??p).map((x,i)=>{const q=rec(x);return{id:id(q.id,`canned-${i}`),title:str(q.title,q.name)??'',body:str(q.body,q.response)??'',category:str(q.category)?.toUpperCase() as SupportCannedResponse['category']};});}
const refresh=async(idValue:string)=>getSupportTicket(idValue);
export async function assignSupportTicket(idValue:string,input:AssignTicketInput,_actor:AdminSession){await apiClient.post(`/api/dashboard/support/tickets/${encodeURIComponent(idValue)}/assign`,{adminId:input.assigneeId});return refresh(idValue);}
export async function changeSupportPriority(idValue:string,input:ChangePriorityInput,_actor:AdminSession){await apiClient.patch(`/api/dashboard/support/tickets/${encodeURIComponent(idValue)}/priority`,{priority:input.priority});return refresh(idValue);}
export async function changeSupportStatus(idValue:string,status:SupportTicketStatus,_actor:AdminSession){await apiClient.patch(`/api/dashboard/support/tickets/${encodeURIComponent(idValue)}/status`,{status});return refresh(idValue);}
export async function replyToSupportTicket(idValue:string,input:ReplyTicketInput,_actor:AdminSession){await apiClient.post(`/api/dashboard/support/tickets/${encodeURIComponent(idValue)}/replies`,{body:input.body,attachments:[]});if(input.waitForUser)await apiClient.patch(`/api/dashboard/support/tickets/${encodeURIComponent(idValue)}/status`,{status:'WAITING_FOR_USER'});return refresh(idValue);}
export async function addSupportInternalNote(idValue:string,body:string,_actor:AdminSession){await apiClient.post(`/api/dashboard/support/tickets/${encodeURIComponent(idValue)}/internal-notes`,{body});return refresh(idValue);}
export async function escalateSupportTicket(idValue:string,input:EscalateTicketInput,_actor:AdminSession){await apiClient.post(`/api/dashboard/support/tickets/${encodeURIComponent(idValue)}/escalate`,{reason:`[${input.targetTeam}] ${input.reason}`});return refresh(idValue);}
export async function resolveSupportTicket(idValue:string,input:ResolveTicketInput,_actor:AdminSession){await apiClient.post(`/api/dashboard/support/tickets/${encodeURIComponent(idValue)}/resolve`,{reason:input.summary,resolution:input.summary});return refresh(idValue);}
export async function closeSupportTicket(idValue:string,_actor:AdminSession){await apiClient.post(`/api/dashboard/support/tickets/${encodeURIComponent(idValue)}/close`);return refresh(idValue);}
export async function reopenSupportTicket(idValue:string,input:ReopenTicketInput,_actor:AdminSession){await apiClient.post(`/api/dashboard/support/tickets/${encodeURIComponent(idValue)}/reopen`,{reason:input.reason});return refresh(idValue);}
