import { Link } from 'react-router';
import { Building2, ExternalLink, FileText, HeartHandshake, Star } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { toast } from 'sonner';
import { Badge, Button, Card, SectionHeader, Textarea } from '@/components/ui';
import { DocumentReviewList } from '@/components/ui/document-review-list';
import { WeeklyOperatingHours } from '@/components/ui/weekly-operating-hours';
import { LocationPreview } from '@/components/ui/location-preview';
import { OperationalTimeline } from '@/components/ui/operational-timeline';
import { usePermission } from '@/features/auth/rbac';
import { useAdvertiserAdvertisementSummary } from '@/features/advertisements/hooks';
import { dayLabels, documentTypeLabels, organizationServiceLabels } from '../constants';
import { organizationNoteSchema } from '../schemas';
import { useAddOrganizationNote, useReviewOrganizationDocument } from '../hooks';
import type { OrganizationDetails } from '../types';
import { formatOrganizationDate, formatOrganizationRelative } from '../utils';
import { VerificationBadge } from './organization-badges';
export function OverviewCard({details}:{details:OrganizationDetails}){const o=details.organization;return <Card><SectionHeader title="نظرة عامة"/><p className="mt-4 text-sm leading-7 text-muted-foreground">{o.description}</p><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Info l="رقم التسجيل" v={o.registrationNumber??'—'}/><Info l="رقم الترخيص" v={o.licenseNumber??'—'}/><Info l="سنة التأسيس" v={String(o.foundedYear??'—')}/><Info l="الهاتف" v={o.phone}/><Info l="البريد" v={o.email}/><Info l="الممثل الأساسي" v={`${o.primaryContact.name} — ${o.primaryContact.role}`}/></dl></Card>}
function Info({l,v}:{l:string;v:string}){return <div><dt className="text-xs text-muted-foreground">{l}</dt><dd className="mt-1 text-sm font-semibold">{v}</dd></div>}
export function VerificationCard({details}:{details:OrganizationDetails}){const o=details.organization;const missing=o.documents.filter(d=>d.required&&d.status!=='VERIFIED');return <Card><SectionHeader title="التحقق والامتثال" actions={<VerificationBadge status={o.verificationStatus}/>}/>{missing.length>0&&<div role="alert" className="mt-4 rounded-md border border-pending/30 bg-pending/10 p-3 text-sm">هناك مستندات مطلوبة لم تُعتمد بعد. لا يمكن إكمال الاعتماد قبل تسويتها.</div>}<div className="mt-4 space-y-2">{details.review.checklist.map(c=><div key={c.key} className="flex items-center justify-between rounded-md border p-3 text-sm"><span>{c.label}</span><Badge tone={c.passed?'success':'pending'}>{c.passed?'مكتمل':'غير مكتمل'}</Badge></div>)}</div>{details.review.adminMessage&&<div className="mt-4 rounded-md bg-muted p-3 text-sm"><p className="font-semibold">طلب معلومات إضافية</p><p className="mt-1 text-muted-foreground">{details.review.adminMessage}</p></div>}</Card>}
export function DocumentsCard({details}:{details:OrganizationDetails}){const review=useReviewOrganizationDocument(details.organization.id);const canReview=usePermission('organizations.documents.review');return <Card><SectionHeader title="المستندات" description="مراجعة مستندات التسجيل والتحقق كلٌ على حدة."/><div className="mt-4"><DocumentReviewList documents={details.organization.documents} typeLabels={documentTypeLabels} formatDate={formatOrganizationDate} canReview={canReview} onPreview={()=>toast.info('معاينة الملفات ستتصل بخدمة التخزين الخلفية لاحقاً.')} onApprove={d=>review.mutate({documentId:d.id,input:{decision:'APPROVE'}},{onSuccess:()=>toast.success('تم اعتماد المستند'),onError:()=>toast.error('تعذر اعتماد المستند')})} onReject={d=>review.mutate({documentId:d.id,input:{decision:'REJECT',reason:'المستند يحتاج نسخة أوضح'}},{onSuccess:()=>toast.success('تم رفض المستند مع تسجيل السبب'),onError:()=>toast.error('تعذر تحديث المستند')})}/></div></Card>}
export function ServicesHoursCard({details}:{details:OrganizationDetails}){return <Card><SectionHeader title="الخدمات وساعات العمل"/><div className="mt-4 flex flex-wrap gap-2">{details.organization.services.map(s=><span key={s.key} className="rounded-full bg-info/10 px-2.5 py-1 text-xs font-semibold text-info">{organizationServiceLabels[s.key]}</span>)}</div><div className="mt-5"><WeeklyOperatingHours hours={details.organization.operatingHours} dayLabels={dayLabels}/></div></Card>}
export function LocationCard({details}:{details:OrganizationDetails}){const o=details.organization;if(o.latitude===undefined||o.longitude===undefined)return <Card><SectionHeader title="الموقع"/><p className="mt-4 text-sm text-muted-foreground">لا توجد إحداثيات موثقة لهذا السجل بعد.</p></Card>;return <Card><SectionHeader title="الموقع"/><div className="mt-4"><LocationPreview title={o.name} address={`${o.governorate}${o.city?` — ${o.city}`:''} · ${o.address}`} latitude={o.latitude} longitude={o.longitude} mapHref={`/map?entityType=ORGANIZATION&entityId=${o.id}`}/></div></Card>}
export function OperationsCard({details}:{details:OrganizationDetails}){const o=details.organization,s=o.statistics,canSupport=usePermission('support.read');return <Card><SectionHeader title="الأداء والنشاط التشغيلي"/><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={HeartHandshake} l="بلاغات نشطة" v={s?.activeReports??0}/><Metric icon={HeartHandshake} l="بلاغات مغلقة" v={s?.closedReports??0}/><Metric icon={HeartHandshake} l="عروض تبني بانتظار النشر" v={s?.pendingAdoptionRequests??0}/><Metric icon={Star} l="نسبة إغلاق البلاغات" v={s?.completionRate!==undefined?`${s.completionRate}%`:'—'}/></div><div className="mt-5 flex flex-wrap gap-2"><Link to={`/reports?organization=${o.id}`}><Button variant="secondary">عرض البلاغات المسندة</Button></Link><Link to={`/adoption-requests?organization=${o.id}`}><Button variant="secondary">عرض عروض التبني</Button></Link><Link to={`/feeding-points?organizationId=${o.id}`}><Button variant="secondary">نقاط الإطعام المسؤولة</Button></Link>{canSupport&&<Link to={`/support?organizationId=${o.id}`}><Button variant="secondary">سجل الدعم</Button></Link>}</div><div className="mt-5 grid gap-4 lg:grid-cols-3"><Recent title="أحدث البلاغات" items={details.recentReports.map(x=>({id:x.id,label:x.status,href:`/reports/${x.id}`}))}/><Recent title="أحدث عروض التبني" items={details.recentAdoptions.map(x=>({id:x.id,label:x.applicantName,href:`/adoption-requests/${x.id}`}))}/></div></Card>}
function Metric({icon:Icon,l,v}:{icon:typeof Building2;l:string;v:string|number}){return <div className="rounded-lg border p-3"><Icon className="size-4 text-primary"/><p className="mt-2 text-xs text-muted-foreground">{l}</p><p className="mt-1 text-lg font-bold">{v}</p></div>}
function Recent({title,items}:{title:string;items:Array<{id:string;label:string;href:string}>}){return <div className="rounded-lg border p-3"><p className="font-semibold">{title}</p><div className="mt-3 space-y-2">{items.length?items.slice(0,3).map(x=><Link key={x.id} to={x.href} className="flex justify-between gap-2 text-sm hover:text-primary"><span>{x.id}</span><span className="truncate text-muted-foreground">{x.label}</span></Link>):<p className="text-sm text-muted-foreground">لا توجد بيانات مرتبطة.</p>}</div></div>}
export function OrganizationAdvertisingCard({details}:{details:OrganizationDetails}){const q=useAdvertiserAdvertisementSummary('ORGANIZATION',details.organization.id);return <Card><SectionHeader title="الإعلانات" description="حملات الجمعية المسجلة في نظام الإعلانات الموحد."/><div className="mt-4 rounded-lg border p-4"><FileText className="size-5 text-primary"/><p className="mt-2 font-semibold">الإعلانات</p><p className="mt-1 text-sm text-muted-foreground">{q.data?.active??0} فعالة · {q.data?.pending??0} بانتظار المراجعة · {q.data?.paused??0} متوقفة</p><Link to={`/advertisements?organizationId=${details.organization.id}`} className="mt-3 inline-flex text-sm font-semibold text-primary">عرض كل الإعلانات <ExternalLink className="ms-1 size-4"/></Link></div></Card>}
export function TimelineCard({details}:{details:OrganizationDetails}){return <Card><SectionHeader title="سجل النشاط"/><div className="mt-4"><OperationalTimeline items={details.timeline.map(e=>({id:e.id,title:e.action,actor:e.actor,timestampLabel:formatOrganizationRelative(e.timestamp),details:e.details,tone:e.tone}))}/></div></Card>}
type NoteForm={note:string}; export function NotesCard({details}:{details:OrganizationDetails}){const mutation=useAddOrganizationNote(details.organization.id);const{register,handleSubmit,reset,formState:{errors}}=useForm<NoteForm>({resolver:zodResolver(organizationNoteSchema),defaultValues:{note:''}});return <Card><SectionHeader title="ملاحظات داخلية" description="لا تظهر هذه الملاحظات للجمعية."/><form className="mt-4 space-y-2" onSubmit={e=>{e.preventDefault();void handleSubmit(v=>mutation.mutate(v.note,{onSuccess:()=>{toast.success('أضيفت الملاحظة');reset();},onError:()=>toast.error('تعذر إضافة الملاحظة')}))();}}><Textarea aria-label="ملاحظة داخلية" {...register('note')} placeholder="أضف ملاحظة لفريق الإدارة…"/>{errors.note&&<p className="text-xs text-critical">{errors.note.message}</p>}<Button type="submit" disabled={mutation.isPending}>إضافة ملاحظة</Button></form><div className="mt-4 space-y-3">{details.notes.map(n=><div key={n.id} className="rounded-md bg-muted/60 p-3 text-sm"><div className="flex justify-between gap-2"><strong>{n.adminName}</strong><span className="text-xs text-muted-foreground">{formatOrganizationRelative(n.createdAt)}</span></div><p className="mt-1 text-muted-foreground">{n.note}</p></div>)}</div></Card>}
