import { ExternalLink, Mail, Phone } from 'lucide-react';
import { Badge, Button } from '@/components/ui';
import { entityTypeLabels } from '../constants';
import type { MapEntity } from '../types';
export function MapEntityPanel({entity}:{entity?:MapEntity}){
 if(!entity)return <div className="rounded-xl border border-border/45 bg-white p-4"><p className="text-[13px] font-semibold">تفاصيل المكان</p><p className="mt-1.5 text-[12px] leading-5 text-muted-foreground">اختر أي علامة من الخريطة لعرض معلومات المكان والتواصل.</p></div>;
 const m=entity.metadata;
 return <div className="rounded-xl border border-border/45 bg-white p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><Badge tone="info">{entityTypeLabels[entity.type]}</Badge><h2 className="mt-2 text-[15px] font-semibold">{entity.title}</h2><p className="mt-1 text-[11px] text-muted-foreground">{entity.governorate}{entity.city?` — ${entity.city}`:''}</p></div></div><p className="mt-3 text-[12px] leading-5 text-muted-foreground">{m.description??entity.address}</p><dl className="mt-4 space-y-2 border-t border-border/35 pt-3 text-[12px]"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">العنوان</dt><dd className="text-end font-medium">{entity.address}</dd></div>{m.openingHours&&<div className="flex justify-between gap-3"><dt className="text-muted-foreground">ساعات العمل</dt><dd className="font-medium">{m.openingHours}</dd></div>}{m.ownerName&&<div className="flex justify-between gap-3"><dt className="text-muted-foreground">الجهة</dt><dd className="font-medium">{m.ownerName}</dd></div>}</dl><div className="mt-4 flex flex-wrap gap-2">{m.phone&&<a href={`tel:${m.phone}`}><Button size="sm" variant="secondary"><Phone className="size-4"/>اتصال</Button></a>}{m.email&&<a href={`mailto:${m.email}`}><Button size="sm" variant="secondary"><Mail className="size-4"/>بريد</Button></a>}<Button size="sm" variant="ghost" onClick={()=>window.open(`https://www.google.com/maps?q=${entity.coordinates.latitude},${entity.coordinates.longitude}`,'_blank','noopener,noreferrer')}><ExternalLink className="size-4"/>فتح الموقع</Button></div></div>;
}
