import type{AuditEvent,AuditResourceType,AuditValue}from'../types';import type{Permission}from'@/features/auth/permissions';import{auditResourceLabels,sensitiveFields}from'../constants';import{safeDate,safeFormatDate}from'@/lib/runtime-safety';
export function formatAuditTimestamp(value:string){return safeFormatDate(value,{dateStyle:'long',timeStyle:'medium',timeZone:'Asia/Damascus'});}
export function formatAuditRelative(value:string){const date=safeDate(value);if(!date)return'—';const d=Date.now()-date.getTime(),m=Math.max(0,Math.round(d/60000));if(m<60)return`منذ ${m||1} دقيقة`;const h=Math.round(m/60);if(h<24)return`منذ ${h} ساعة`;return`منذ ${Math.round(h/24)} يوم`;}
export function resourcePath(type:AuditResourceType,id:string){if(type==='CONTENT'){const root=id.startsWith('ST-')?'/content/success-stories':id.startsWith('AWR-')?'/content/awareness':'/content/articles';return `${root}/${id}`;}if(type==='SYSTEM_SETTING')return'/settings/system';const roots:Partial<Record<AuditResourceType,string>>={REPORT:'/reports',RESCUE_MISSION:'/reports',ADOPTION_REQUEST:'/adoption-requests',ORGANIZATION:'/organizations',USER:'/users',FEEDING_POINT:'/feeding-points',DONATION:'/donations',ADVERTISEMENT:'/advertisements',NOTIFICATION:'/notifications',SUPPORT_TICKET:'/support',ADMIN:'/settings/admin-users',ROLE:'/settings/roles'};const root=roots[type];return root?`${root}/${id}`:undefined;}
export function resourcePermission(type:AuditResourceType):Permission|undefined{const p:Partial<Record<AuditResourceType,Permission>>={REPORT:'reports:view',RESCUE_MISSION:'missions:view',ADOPTION_REQUEST:'adoption:read',ORGANIZATION:'organizations:read',USER:'users:read',FEEDING_POINT:'feeding_points.read',DONATION:'donations.read',ADVERTISEMENT:'advertisements.read',CONTENT:'content.read',NOTIFICATION:'notifications.read',SUPPORT_TICKET:'support.read',ADMIN:'admins.read',ROLE:'roles.read',SYSTEM_SETTING:'settings.read'};return p[type];}
export function valueRows(value:AuditValue|undefined,canSensitive:boolean){if(value===undefined)return[];if(value===null||typeof value!=='object')return[{field:'القيمة',value:String(value)}];return Object.entries(value).map(([field,v])=>({field,value:!canSensitive&&sensitiveFields.has(field)?'••••••':String(v??'—')}));}
export function auditCsv(events:AuditEvent[],includeTechnical:boolean){const quote=(v:string)=>`"${v.replaceAll('"','""')}"`;const headers=['eventId','timestamp','actor','role','action','resourceType','resourceId','reason','source',...(includeTechnical?['correlationId']:[])];const lines=[headers.join(',')];for(const e of events)lines.push([e.id,e.timestamp,e.actor.name,e.actor.role??'',e.action,e.resource.type,e.resource.id,e.reason??'',e.metadata?.source??'',...(includeTechnical?[e.requestContext?.correlationId??'']:[])].map(v=>quote(v)).join(','));return '\uFEFF'+lines.join('\n');}
export function downloadTextFile(name:string,text:string,type:string){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function resourceLabel(type:AuditResourceType){return auditResourceLabels[type];}
