import { getOrganizations } from '@/features/organizations/services/organizations.mock';
import { getFeedingPoints } from '@/features/feeding-points/services/feeding-points.mock';
import { mockDelay } from '@/services/mock/delay';
import type { CreateMapListingInput, MapDirectoryData, MapEntity, MapListingRequest } from '../types';

const now=()=>new Date().toISOString();
let sequence=20;
let directory:MapEntity[]=[
 {id:'MAP:PET-001',sourceId:'PET-001',type:'PET_SUPPLIES',coordinates:{latitude:33.5149,longitude:36.2765},title:'بيت الحيوان للمستلزمات',subtitle:'متجر مستلزمات',governorate:'دمشق',city:'المزة',address:'أوتستراد المزة، دمشق',updatedAt:now(),metadata:{source:'USER_REQUEST',reviewStatus:'APPROVED',status:'ACTIVE',ownerType:'USER',ownerName:'رامي الأحمد',phone:'0944001122',openingHours:'10:00 - 22:00',description:'مستلزمات وطعام وأدوات عناية للحيوانات.'}},
 {id:'MAP:VET-002',sourceId:'VET-002',type:'VET_CLINIC',coordinates:{latitude:33.5102,longitude:36.2981},title:'عيادة الرفق البيطرية',subtitle:'عيادة بيطرية',governorate:'دمشق',city:'أبو رمانة',address:'أبو رمانة، دمشق',updatedAt:now(),metadata:{source:'ADMIN',reviewStatus:'APPROVED',status:'ACTIVE',ownerType:'ADMIN',ownerName:'إدارة ResQ',phone:'0113344556',email:'care@example.test',openingHours:'09:00 - 20:00'}},
 {id:'MAP:PHARM-003',sourceId:'PHARM-003',type:'ANIMAL_PHARMACY',coordinates:{latitude:36.2017,longitude:37.1343},title:'مستودع الشفاء البيطري',governorate:'حلب',city:'الجميلية',address:'الجميلية، حلب',updatedAt:now(),metadata:{source:'USER_REQUEST',reviewStatus:'APPROVED',status:'ACTIVE',ownerType:'USER',ownerName:'محمود سليمان',phone:'0933554411'}},
 {id:'MAP:HOTEL-004',sourceId:'HOTEL-004',type:'CAT_HOTEL',coordinates:{latitude:33.5251,longitude:36.2852},title:'بيت القطط للاستضافة',governorate:'دمشق',city:'المالكي',address:'المالكي، دمشق',updatedAt:now(),metadata:{source:'ADMIN',reviewStatus:'APPROVED',status:'ACTIVE',ownerType:'ADMIN',ownerName:'إدارة ResQ',phone:'0955007744'}},
 {id:'MAP:CAFE-005',sourceId:'CAFE-005',type:'CAT_CAFE',coordinates:{latitude:33.5124,longitude:36.2914},title:'Cat Corner',governorate:'دمشق',city:'الشعلان',address:'الشعلان، دمشق',updatedAt:now(),metadata:{source:'USER_REQUEST',reviewStatus:'APPROVED',status:'ACTIVE',ownerType:'USER',ownerName:'نور جابر',phone:'0999221100',email:'hello@catcorner.example'}},
 {id:'MAP:ZOO-006',sourceId:'ZOO-006',type:'ZOO',coordinates:{latitude:33.468,longitude:36.212},title:'حديقة الحيوانات التعليمية',governorate:'ريف دمشق',city:'قدسيا',address:'قدسيا، ريف دمشق',updatedAt:now(),metadata:{source:'ADMIN',reviewStatus:'APPROVED',status:'ACTIVE',ownerType:'ADMIN',ownerName:'إدارة ResQ'}},
];
let requests:MapListingRequest[]=[
 {id:'MAP:REQ-101',sourceId:'REQ-101',type:'VET_CLINIC',coordinates:{latitude:34.7308,longitude:36.709},title:'عيادة الرحمة البيطرية',governorate:'حمص',city:'الإنشاءات',address:'حي الإنشاءات، حمص',updatedAt:now(),metadata:{source:'USER_REQUEST',reviewStatus:'PENDING',status:'ACTIVE',ownerType:'USER',ownerName:'سارة الحسن',phone:'0944556677',description:'عيادة للحيوانات الأليفة مع قسم إسعاف.',submittedAt:now(),imageUrl:'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=900&q=80'}},
 {id:'MAP:REQ-102',sourceId:'REQ-102',type:'PET_SUPPLIES',coordinates:{latitude:35.5317,longitude:35.7901},title:'مخزن أصدقاء الحيوانات',governorate:'اللاذقية',city:'المشروع السابع',address:'المشروع السابع، اللاذقية',updatedAt:now(),metadata:{source:'USER_REQUEST',reviewStatus:'PENDING',status:'ACTIVE',ownerType:'USER',ownerName:'عمر المصري',phone:'0933112211',submittedAt:now()}},
];

async function automaticEntities():Promise<MapEntity[]>{
 const [orgs,feeding]=await Promise.all([
  getOrganizations({search:'',page:1,pageSize:250,sortBy:'updatedAt',sortDirection:'desc'}),
  getFeedingPoints({search:'',page:1,pageSize:250,sortBy:'updatedAt',sortDirection:'desc'}),
 ]);
 const organizations:MapEntity[]=orgs.items.filter(o=>o.status==='ACTIVE'&&o.verificationStatus==='VERIFIED'&&o.latitude!==undefined&&o.longitude!==undefined).map(o=>({id:`ORGANIZATION:${o.id}`,sourceId:o.id,type:'ORGANIZATION',coordinates:{latitude:o.latitude!,longitude:o.longitude!},title:o.name,subtitle:'جمعية موثقة',governorate:o.governorate,city:o.city,address:o.address,updatedAt:o.updatedAt,metadata:{source:'ORGANIZATION_AUTO',reviewStatus:'APPROVED',status:'ACTIVE',ownerType:'ORGANIZATION',ownerName:o.name,phone:o.phone,email:o.email,website:o.website,description:o.description}}));
 const points:MapEntity[]=feeding.items.filter(p=>p.status==='ACTIVE').map(p=>({id:`FEEDING_POINT:${p.id}`,sourceId:p.id,type:'FEEDING_POINT',coordinates:{latitude:p.location.latitude,longitude:p.location.longitude},title:p.name??'نقطة إطعام',subtitle:p.id,governorate:p.location.governorate,city:p.location.city,address:p.location.address,updatedAt:p.updatedAt,metadata:{source:'FEEDING_POINT_AUTO',reviewStatus:'APPROVED',status:'ACTIVE',ownerType:'SYSTEM',ownerName:p.createdBy.name,description:p.description}}));
 return [...organizations,...points];
}
export async function getOperationalMapData():Promise<MapDirectoryData>{await mockDelay(90);return{entities:[...directory.filter(x=>x.metadata.reviewStatus==='APPROVED'),...(await automaticEntities())],requests:structuredClone(requests),generatedAt:now()};}
export async function createMapListing(input:CreateMapListingInput){await mockDelay(90);sequence+=1;const id=`MAN-${String(sequence).padStart(3,'0')}`;const item:MapEntity={id:`MAP:${id}`,sourceId:id,type:input.type,coordinates:{latitude:input.latitude,longitude:input.longitude},title:input.title,governorate:input.governorate,city:input.city,address:input.address,updatedAt:now(),metadata:{source:'ADMIN',reviewStatus:'APPROVED',status:'ACTIVE',ownerType:'ADMIN',ownerName:input.ownerName,description:input.description,phone:input.phone,email:input.email,website:input.website,openingHours:input.openingHours}};directory=[item,...directory];return structuredClone(item);}
export async function approveMapListing(id:string){await mockDelay(70);const index=requests.findIndex(x=>x.id===id);if(index<0)throw new Error('MAP_REQUEST_NOT_FOUND');const req=requests[index]!;const approved:MapEntity={...req,updatedAt:now(),metadata:{...req.metadata,reviewStatus:'APPROVED'}};requests=requests.map((x,i)=>i===index?({...x,updatedAt:approved.updatedAt,metadata:{...x.metadata,reviewStatus:'APPROVED'}} as MapListingRequest):x);directory=[approved,...directory.filter(x=>x.id!==id)];return structuredClone(approved);}
export async function rejectMapListing(id:string,reason:string){await mockDelay(70);requests=requests.map(x=>x.id===id?({...x,updatedAt:now(),metadata:{...x.metadata,reviewStatus:'REJECTED',rejectionReason:reason}} as MapListingRequest):x);return true;}
export async function toggleMapListing(id:string){await mockDelay(60);directory=directory.map(x=>x.id===id?({...x,updatedAt:now(),metadata:{...x.metadata,status:x.metadata.status==='ACTIVE'?'INACTIVE':'ACTIVE'}}):x);return true;}
export async function deleteMapListing(id:string){await mockDelay(60);directory=directory.filter(x=>x.id!==id);requests=requests.filter(x=>x.id!==id);return true;}
