import { useState } from 'react';
import { useNavigate, useParams, Link } from 'react-router';
import { Check, Trash2, X } from 'lucide-react';
import { toast } from 'sonner';
import { Button, Card, ErrorState, Skeleton } from '@/components/ui';
import { PermissionGuard } from '@/features/auth/rbac';
import { useApproveDonationCampaign, useDonationCampaign } from '../hooks';
import { DonationCampaignStatusBadge } from '../components/donation-badges';
import { DeleteDonationCampaignDialog, RejectDonationCampaignDialog } from '../components/donation-workflow-dialogs';
import { formatDonationDate, formatMoney } from '../utils';

export function DonationDetailsPage() {
  const { donationId = '' } = useParams();
  const navigate = useNavigate();
  const query = useDonationCampaign(donationId);
  const approve = useApproveDonationCampaign(donationId);
  const [rejectOpen, setRejectOpen] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  if (query.isLoading) return <div className="space-y-4"><Skeleton className="h-24 rounded-xl" /><Skeleton className="h-80 rounded-xl" /></div>;
  if (query.isError) return <ErrorState title="تعذر تحميل الحملة" description={query.error.message} onRetry={() => void query.refetch()} />;
  if (!query.data) return <ErrorState title="الحملة غير موجودة" description="قد تكون الحملة محذوفة أو أن الرابط غير صحيح." />;
  const { campaign, donors, timeline } = query.data;
  return <div className="space-y-4" dir="rtl">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-1.5 text-[11px] text-muted-foreground/70"><Link to="/donations">التبرعات</Link><span>/</span><span>{campaign.id}</span></div><h1 className="mt-1 text-[19px] font-semibold leading-6">{campaign.title}</h1><p className="mt-0.5 text-[12px] text-muted-foreground/75">طلب نشر من {campaign.publisher.name} لصالح {campaign.beneficiaryOrganization.name}</p></div><div className="flex flex-wrap items-center gap-2"><DonationCampaignStatusBadge status={campaign.status} />{campaign.status === 'PENDING_REVIEW' && <><PermissionGuard permission="donations.read"><Button className="h-9 rounded-xl text-[12px]" disabled={approve.isPending} onClick={() => approve.mutate(undefined, { onSuccess: () => toast.success('تمت الموافقة ونشر الحملة'), onError: () => toast.error('تعذر نشر الحملة') })}><Check className="size-4" />موافقة ونشر</Button></PermissionGuard><Button variant="secondary" className="h-9 rounded-xl text-[12px]" onClick={() => setRejectOpen(true)}><X className="size-4" />رفض النشر</Button></>}<Button variant="ghost" className="h-9 rounded-xl text-[12px] text-critical" onClick={() => setDeleteOpen(true)}><Trash2 className="size-4" />حذف</Button></div></div>
    <Card className="overflow-hidden rounded-xl border-border/45 bg-white p-0 shadow-none"><div className="grid lg:grid-cols-[minmax(0,1fr)_19rem]"><main className="p-4 lg:border-e lg:border-border/40"><div className="flex items-start gap-4"><img src={campaign.media[0]?.url} alt={campaign.media[0]?.alt ?? campaign.title} className="h-28 w-36 shrink-0 rounded-lg object-cover" /><div><p className="text-[14px] font-semibold">محتوى الحملة</p><p className="mt-2 text-[12px] leading-6 text-muted-foreground">{campaign.description}</p></div></div><div className="mt-4 grid gap-3 border-t border-border/35 pt-4 sm:grid-cols-3"><div><p className="text-[11px] text-muted-foreground">المبلغ المجموع</p><p className="mt-1 text-[14px] font-semibold">{formatMoney(campaign.raisedAmountMinor, campaign.currency)}</p></div><div><p className="text-[11px] text-muted-foreground">الهدف المعلن</p><p className="mt-1 text-[14px] font-semibold">{campaign.targetAmountMinor ? formatMoney(campaign.targetAmountMinor, campaign.currency) : 'غير محدد'}</p></div><div><p className="text-[11px] text-muted-foreground">عدد المتبرعين</p><p className="mt-1 text-[14px] font-semibold">{campaign.donorCount}</p></div></div>{campaign.rejectionReason && <div className="mt-4 rounded-lg border border-critical/15 bg-critical/[0.035] p-3"><p className="text-[12px] font-semibold text-critical">سبب الرفض</p><p className="mt-1 text-[12px] text-muted-foreground">{campaign.rejectionReason}</p></div>}</main><aside className="space-y-4 bg-muted/[0.12] p-4"><div><p className="text-[12px] font-semibold">صاحب الحملة</p><p className="mt-1 text-[12px]">{campaign.publisher.name}</p><p className="text-[11px] text-muted-foreground">{campaign.publisher.id}</p></div><div className="border-t border-border/35 pt-3"><p className="text-[12px] font-semibold">الجمعية المستفيدة</p><p className="mt-1 text-[12px]">{campaign.beneficiaryOrganization.name}</p><p className="text-[11px] text-muted-foreground">{campaign.beneficiaryOrganization.id}</p></div><div className="border-t border-border/35 pt-3"><p className="text-[11px] text-muted-foreground">تاريخ التقديم</p><p className="mt-1 text-[12px]">{formatDonationDate(campaign.submittedAt)}</p></div></aside></div></Card>
    <Card className="rounded-xl border-border/45 bg-white p-4 shadow-none"><div className="flex items-end justify-between gap-3"><div><h2 className="text-[14px] font-semibold">أرشيف المتبرعين</h2><p className="mt-0.5 text-[11px] text-muted-foreground/75">لا تظهر بيانات الدفع، أرقام العمليات، أرقام الهواتف أو البريد الإلكتروني للإدارة.</p></div><span className="text-[11px] text-muted-foreground">{donors.length} سجلات ظاهرة</span></div><div className="mt-3 divide-y divide-border/35">{donors.length ? donors.map((donor) => <div key={donor.id} className="flex items-center justify-between gap-3 py-2.5 first:pt-0 last:pb-0"><div><p className="text-[12px] font-medium">{donor.anonymous ? 'متبرع مجهول' : donor.displayName}</p><p className="text-[11px] text-muted-foreground">{formatDonationDate(donor.donatedAt)}</p></div><p className="text-[12px] font-semibold">{formatMoney(donor.amountMinor, donor.currency)}</p></div>) : <p className="py-5 text-center text-[12px] text-muted-foreground">لا توجد تبرعات مؤرشفة لهذه الحملة بعد.</p>}</div></Card>
    <Card className="rounded-xl border-border/45 bg-white p-4 shadow-none"><h2 className="text-[14px] font-semibold">سجل الحملة</h2><div className="mt-3 divide-y divide-border/35">{timeline.map((event) => <div key={event.id} className="py-2.5 first:pt-0 last:pb-0"><div className="flex items-center justify-between gap-3"><p className="text-[12px] font-medium">{event.title}</p><span className="text-[11px] text-muted-foreground">{formatDonationDate(event.timestamp)}</span></div>{event.details && <p className="mt-1 text-[11px] text-muted-foreground">{event.details}</p>}</div>)}</div></Card>
    <RejectDonationCampaignDialog campaignId={campaign.id} open={rejectOpen} onOpenChange={setRejectOpen} /><DeleteDonationCampaignDialog campaignId={campaign.id} open={deleteOpen} onOpenChange={setDeleteOpen} onDeleted={() => navigate('/donations')} />
  </div>;
}
