import * as CheckboxPrimitive from '@radix-ui/react-checkbox';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import * as DropdownPrimitive from '@radix-ui/react-dropdown-menu';
import * as RadioGroupPrimitive from '@radix-ui/react-radio-group';
import * as SelectPrimitive from '@radix-ui/react-select';
import * as SwitchPrimitive from '@radix-ui/react-switch';
import * as TabsPrimitive from '@radix-ui/react-tabs';
import * as TooltipPrimitive from '@radix-ui/react-tooltip';
import { Check, ChevronDown, ChevronLeft, ChevronRight, Search, X, type LucideIcon } from 'lucide-react';
import { forwardRef, useEffect, useRef, useState, type ButtonHTMLAttributes, type HTMLAttributes, type InputHTMLAttributes, type ReactNode, type TextareaHTMLAttributes } from 'react';
import { Link } from 'react-router';
import { cn } from '@/lib/cn';
import { safeDisplayText } from '@/lib/runtime-safety';
import { getStatusMeta, type SemanticStatus, type StatusTone } from '@/lib/statuses';

const focusRing = 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/75 focus-visible:ring-offset-2 focus-visible:ring-offset-background';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';
export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> { variant?: ButtonVariant; size?: 'sm' | 'md' | 'lg'; }
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button({ className, variant = 'primary', size = 'md', type = 'button', ...props }, ref) {
  const variants: Record<ButtonVariant, string> = {
    primary: 'bg-primary text-primary-foreground hover:bg-primary/92',
    secondary: 'border border-border/50 bg-white text-foreground hover:border-primary/20 hover:bg-primary/[0.025]',
    ghost: 'text-foreground hover:bg-primary/[0.035]',
    danger: 'bg-critical text-white hover:bg-critical/90',
  };
  const sizes = { sm: 'h-9 px-3 text-[12px]', md: 'h-9 px-3.5 text-[12px]', lg: 'h-10 px-4 text-[13px]' };
  return <button ref={ref} type={type} className={cn('inline-flex items-center justify-center gap-2 rounded-xl font-medium transition-[background-color,border-color,color] duration-150 disabled:pointer-events-none disabled:opacity-50', focusRing, variants[variant], sizes[size], className)} {...props} />;
});

export function IconButton({ label, className, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string }) {
  return <button type="button" aria-label={label} title={label} className={cn('inline-flex size-9 items-center justify-center rounded-xl text-muted-foreground transition-colors duration-150 hover:bg-primary/[0.035] hover:text-foreground', focusRing, className)} {...props} />;
}

export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(function Input({ className, ...props }, ref) {
  return <input ref={ref} className={cn('h-9 w-full rounded-xl border border-border/50 bg-white px-3 text-[12px] shadow-none transition-[border-color,background-color] duration-150 placeholder:text-muted-foreground/70 hover:border-primary/20 focus:border-primary/30 disabled:cursor-not-allowed disabled:bg-muted/35 disabled:opacity-65', focusRing, className)} {...props} />;
});
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement>>(function Textarea({ className, ...props }, ref) {
  return <textarea ref={ref} className={cn('min-h-24 w-full resize-y rounded-xl border border-border/50 bg-white px-3 py-2.5 text-[12px] leading-6 shadow-none transition-[border-color,background-color] duration-150 placeholder:text-muted-foreground/70 hover:border-primary/20 focus:border-primary/30 disabled:cursor-not-allowed disabled:bg-muted/35 disabled:opacity-65', focusRing, className)} {...props} />;
});

export function Select({ value, onValueChange, options, placeholder = 'اختر', className, disabled = false }: { value?: string; onValueChange?: (value: string) => void; options: Array<{ value: string; label: string }>; placeholder?: string; className?: string; disabled?: boolean }) {
  return <SelectPrimitive.Root value={value} onValueChange={onValueChange} dir="rtl" disabled={disabled}><SelectPrimitive.Trigger className={cn('flex h-9 min-w-0 items-center justify-between gap-2 rounded-xl border border-border/50 bg-white px-3 text-[12px] shadow-none transition-[border-color,background-color] duration-150 hover:border-primary/20 hover:bg-primary/[0.02] focus:border-primary/30 data-[disabled]:cursor-not-allowed data-[disabled]:bg-muted/35 data-[disabled]:opacity-65', focusRing, className)}><SelectPrimitive.Value placeholder={placeholder} /><SelectPrimitive.Icon className="text-muted-foreground"><ChevronDown className="size-4 transition-transform duration-150" /></SelectPrimitive.Icon></SelectPrimitive.Trigger><SelectPrimitive.Portal><SelectPrimitive.Content position="popper" sideOffset={6} collisionPadding={12} className="resq-popover z-50 max-h-[min(22rem,var(--radix-select-content-available-height))] min-w-[var(--radix-select-trigger-width)] max-w-[min(92vw,24rem)] overflow-hidden rounded-xl border border-border/80 bg-surface p-1.5 shadow-overlay"><SelectPrimitive.Viewport>{options.map((option) => <SelectPrimitive.Item key={option.value} value={option.value} className="relative flex min-h-10 cursor-default select-none items-center rounded-lg py-2 pe-9 ps-3 text-sm outline-none transition-colors data-[highlighted]:bg-primary/8 data-[highlighted]:text-foreground data-[state=checked]:font-semibold"><SelectPrimitive.ItemText>{option.label}</SelectPrimitive.ItemText><SelectPrimitive.ItemIndicator className="absolute end-2.5 text-primary"><Check className="size-4" /></SelectPrimitive.ItemIndicator></SelectPrimitive.Item>)}</SelectPrimitive.Viewport></SelectPrimitive.Content></SelectPrimitive.Portal></SelectPrimitive.Root>;
}

export function Checkbox({ checked, onCheckedChange, label, ariaLabel, disabled = false }: { checked?: boolean | 'indeterminate'; onCheckedChange?: (checked: boolean | 'indeterminate') => void; label?: string; ariaLabel?: string; disabled?: boolean }) {
  return <label className={cn('inline-flex items-center gap-2 text-sm', disabled && 'cursor-not-allowed opacity-60')}><CheckboxPrimitive.Root aria-label={ariaLabel} checked={checked} onCheckedChange={onCheckedChange} disabled={disabled} className={cn('flex size-5 items-center justify-center rounded-md border border-border/90 bg-surface shadow-sm transition-[border-color,background-color,box-shadow] data-[state=checked]:border-primary data-[state=checked]:bg-primary data-[state=checked]:text-white data-[state=indeterminate]:border-primary data-[state=indeterminate]:bg-primary data-[state=indeterminate]:text-white disabled:cursor-not-allowed', focusRing)}><CheckboxPrimitive.Indicator><Check className="size-3.5" /></CheckboxPrimitive.Indicator></CheckboxPrimitive.Root>{label}</label>;
}
export function Radio({ value, label }: { value: string; label: string }) { return <label className="inline-flex items-center gap-2 text-sm"><RadioGroupPrimitive.Item value={value} className={cn('flex size-5 items-center justify-center rounded-full border', focusRing)}><RadioGroupPrimitive.Indicator className="size-2.5 rounded-full bg-primary" /></RadioGroupPrimitive.Item>{label}</label>; }
export const RadioGroup = RadioGroupPrimitive.Root;
export function Switch({ checked, onCheckedChange, label }: { checked?: boolean; onCheckedChange?: (checked: boolean) => void; label?: string }) { return <label className="inline-flex items-center gap-2 text-sm"><SwitchPrimitive.Root checked={checked} onCheckedChange={onCheckedChange} className={cn('relative h-6 w-11 rounded-full border border-border/70 bg-muted shadow-inner transition-[background-color,border-color] duration-150 data-[state=checked]:border-primary data-[state=checked]:bg-primary', focusRing)}><SwitchPrimitive.Thumb className="block size-5 translate-x-0.5 rounded-full bg-surface shadow-sm transition-transform duration-150 data-[state=checked]:-translate-x-5" /></SwitchPrimitive.Root>{label}</label>; }

export function Badge({ children, tone = 'neutral', className }: { children: ReactNode; tone?: StatusTone; className?: string }) {
  const tones: Record<StatusTone, string> = { neutral: 'bg-muted text-muted-foreground', success: 'bg-success/10 text-success', pending: 'bg-pending/12 text-brown', critical: 'bg-critical/10 text-critical', info: 'bg-info/10 text-info' };
  return <span className={cn('inline-flex items-center rounded-lg border border-transparent px-2 py-1 text-[11px] font-medium', tones[tone], className)}>{children}</span>;
}
export function StatusBadge({ status }: { status: SemanticStatus }) { const meta = getStatusMeta(status); return <Badge tone={meta.tone}>{meta.label}</Badge>; }
export function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn('rounded-xl border border-border/45 bg-white p-4 shadow-none', className)} {...props} />; }
export function MetricCard({ label, value, icon: Icon, helper }: { label: string; value: string | number; icon?: LucideIcon; helper?: string }) { return <Card className="relative overflow-hidden"><div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-l from-transparent via-primary/35 to-transparent" /><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-extrabold tracking-tight">{value}</p>{helper && <p className="mt-1 text-xs leading-5 text-muted-foreground">{helper}</p>}</div>{Icon && <span className="rounded-xl border border-primary/10 bg-primary/10 p-2.5 text-primary"><Icon className="size-5" /></span>}</div></Card>; }
export function Avatar({ name, src, size = 'md' }: { name?: string | null; src?: string | null; size?: 'sm' | 'md' | 'lg' }) {
  const displayName = safeDisplayText(name, 'مستخدم');
  const initials = displayName.split(/\s+/).slice(0, 2).map((part) => part[0]).filter(Boolean).join('') || '؟';
  const sizes = { sm: 'size-8 text-xs', md: 'size-10 text-sm', lg: 'size-12' };
  const [imageFailed, setImageFailed] = useState(false);
  useEffect(() => setImageFailed(false), [src]);
  return src && !imageFailed
    ? <img src={src} alt={displayName} onError={() => setImageFailed(true)} className={cn('rounded-full object-cover', sizes[size])} />
    : <span role="img" aria-label={displayName} className={cn('inline-flex items-center justify-center rounded-full bg-primary/12 font-bold text-primary', sizes[size])}>{initials}</span>;
}

export function Tooltip({ content, children }: { content: ReactNode; children: ReactNode }) { return <TooltipPrimitive.Provider delayDuration={250}><TooltipPrimitive.Root><TooltipPrimitive.Trigger asChild>{children}</TooltipPrimitive.Trigger><TooltipPrimitive.Portal><TooltipPrimitive.Content sideOffset={6} className="z-50 rounded-lg bg-brown px-2.5 py-1.5 text-xs text-white shadow-overlay">{content}<TooltipPrimitive.Arrow className="fill-brown" /></TooltipPrimitive.Content></TooltipPrimitive.Portal></TooltipPrimitive.Root></TooltipPrimitive.Provider>; }
export const DropdownMenu = DropdownPrimitive.Root;
export const DropdownMenuTrigger = DropdownPrimitive.Trigger;
export function DropdownMenuContent({ children, className, align = 'end' }: { children: ReactNode; className?: string; align?: 'start' | 'center' | 'end' }) { return <DropdownPrimitive.Portal><DropdownPrimitive.Content align={align} sideOffset={8} className={cn('resq-popover z-50 min-w-48 rounded-xl border border-border/80 bg-surface p-1.5 shadow-overlay', className)}>{children}</DropdownPrimitive.Content></DropdownPrimitive.Portal>; }
export function DropdownMenuItem({ children, onSelect, className }: { children: ReactNode; onSelect?: () => void; className?: string }) { return <DropdownPrimitive.Item onSelect={onSelect} className={cn('flex min-h-10 cursor-default items-center gap-2 rounded-lg px-3 py-2 text-sm outline-none transition-colors data-[highlighted]:bg-primary/8 data-[highlighted]:text-foreground', className)}>{children}</DropdownPrimitive.Item>; }

export function Modal({ open, onOpenChange, title, description, children, footer }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description?: string; children: ReactNode; footer?: ReactNode }) { return <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}><DialogPrimitive.Portal><DialogPrimitive.Overlay className="resq-dialog-overlay fixed inset-0 z-50 bg-brown/35" /><DialogPrimitive.Content dir="rtl" className="resq-dialog-content fixed left-1/2 top-1/2 z-50 max-h-[min(88dvh,48rem)] w-[min(92vw,36rem)] -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-xl border border-border/50 bg-white p-5 shadow-lg"><div className="pe-8"><DialogPrimitive.Title className="text-[15px] font-semibold">{title}</DialogPrimitive.Title>{description && <DialogPrimitive.Description className="mt-1 text-[12px] text-muted-foreground">{description}</DialogPrimitive.Description>}</div><DialogPrimitive.Close asChild><IconButton label="إغلاق" className="absolute end-4 top-4"><X className="size-5" /></IconButton></DialogPrimitive.Close><div className="mt-5">{children}</div>{footer && <div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:flex-wrap sm:justify-end">{footer}</div>}</DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>; }
export function ConfirmDialog({ open, onOpenChange, title, description, confirmLabel = 'تأكيد', onConfirm, destructive = false }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; confirmLabel?: string; onConfirm: () => void; destructive?: boolean }) { return <Modal open={open} onOpenChange={onOpenChange} title={title} description={description} footer={<><Button variant="secondary" onClick={() => onOpenChange(false)}>إلغاء</Button><Button variant={destructive ? 'danger' : 'primary'} onClick={() => { onConfirm(); onOpenChange(false); }}>{confirmLabel}</Button></>}> <div className={cn('rounded-md border p-3 text-sm', destructive ? 'border-critical/30 bg-critical/5 text-critical' : 'bg-muted')}>لا يمكن التراجع عن هذا الإجراء إذا كان نهائيًا.</div></Modal>; }

export const Tabs = TabsPrimitive.Root;
export const TabsList = TabsPrimitive.List;
export function TabsTrigger({ value, children }: { value: string; children: ReactNode }) { return <TabsPrimitive.Trigger value={value} className="rounded-lg px-3.5 py-2 text-sm font-semibold text-muted-foreground transition-[background-color,color,box-shadow] duration-150 hover:text-foreground data-[state=active]:bg-surface data-[state=active]:text-foreground data-[state=active]:shadow-card">{children}</TabsPrimitive.Trigger>; }
export const TabsContent = TabsPrimitive.Content;

export function Pagination({ page, pageCount, onPageChange }: { page: number; pageCount: number; onPageChange: (page: number) => void }) { return <nav aria-label="التنقل بين الصفحات" className="flex items-center gap-1.5"><IconButton label="الصفحة السابقة" disabled={page <= 1} onClick={() => onPageChange(page - 1)}><ChevronRight className="size-4" /></IconButton><span className="min-w-20 rounded-lg bg-muted/35 px-3 py-2 text-center text-[12px] font-medium text-muted-foreground">{page} من {Math.max(pageCount, 1)}</span><IconButton label="الصفحة التالية" disabled={page >= pageCount} onClick={() => onPageChange(page + 1)}><ChevronLeft className="size-4" /></IconButton></nav>; }
export function Breadcrumbs({ items }: { items: Array<{ label: string; href?: string }> }) { return <nav aria-label="مسار الصفحة"><ol className="flex flex-wrap items-center gap-1.5 text-[11px] text-muted-foreground/70">{items.map((item, index) => <li key={`${item.label}-${index}`} className="flex items-center gap-2">{index > 0 && <ChevronLeft className="size-3.5" aria-hidden="true" />}{item.href ? <Link className="transition-colors duration-150 hover:text-foreground" to={item.href}>{item.label}</Link> : <span aria-current="page" className="text-foreground">{item.label}</span>}</li>)}</ol></nav>; }
export function Skeleton({ className }: { className?: string }) { return <div aria-hidden="true" className={cn('resq-skeleton overflow-hidden rounded-md bg-muted', className)} />; }
export function EmptyState({ title = 'لا توجد بيانات', description = 'لا توجد عناصر لعرضها حاليًا.', action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="flex min-h-40 flex-col items-center justify-center rounded-lg border border-dashed p-6 text-center"><p className="font-semibold">{title}</p><p className="mt-1 max-w-md text-sm text-muted-foreground">{description}</p>{action && <div className="mt-4">{action}</div>}</div>; }
export function ErrorState({ title = 'تعذر تحميل البيانات', description = 'حدث خطأ غير متوقع. حاول مرة أخرى.', onRetry }: { title?: string; description?: string; onRetry?: () => void }) { return <div role="alert" className="flex min-h-40 flex-col items-center justify-center rounded-lg border border-critical/20 bg-critical/5 p-6 text-center"><p className="font-semibold text-critical">{title}</p><p className="mt-1 max-w-md text-sm text-muted-foreground">{description}</p>{onRetry && <Button className="mt-4" variant="secondary" onClick={onRetry}>إعادة المحاولة</Button>}</div>; }

export function SearchInput({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <div className={cn('relative', className)}><Search className="pointer-events-none absolute start-3.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input type="search" className="ps-10" {...props} /></div>; }
export function DebouncedSearchInput({ value = '', onValueChange, debounceMs = 300, ...props }: Omit<InputHTMLAttributes<HTMLInputElement>, 'value' | 'onChange'> & { value?: string; onValueChange: (value: string) => void; debounceMs?: number }) { const [draft, setDraft] = useState(String(value)); const latestOnValueChange = useRef(onValueChange); useEffect(() => { latestOnValueChange.current = onValueChange; }, [onValueChange]); useEffect(() => { const next = String(value); setDraft((current) => current === next ? current : next); }, [value]); useEffect(() => { const next = String(value); if (draft === next) return; const timer = window.setTimeout(() => latestOnValueChange.current(draft), debounceMs); return () => window.clearTimeout(timer); }, [debounceMs, draft, value]); return <SearchInput {...props} value={draft} onChange={(event) => setDraft(event.target.value)} />; }
export function FilterBar({ children }: { children: ReactNode }) { return <div className="resq-filter-bar flex flex-col gap-2 rounded-xl border border-border/45 bg-white p-2.5 shadow-none sm:flex-row sm:flex-wrap sm:items-center">{children}</div>; }
export function PageHeader({ title, description, actions, breadcrumbs }: { title: string; description?: string; actions?: ReactNode; breadcrumbs?: Array<{ label: string; href?: string }> }) { return <header className="space-y-1">{breadcrumbs && <Breadcrumbs items={breadcrumbs} />}<div className="flex flex-col justify-between gap-2.5 sm:flex-row sm:items-start"><div className="min-w-0"><h1 className="text-[19px] font-semibold leading-6 tracking-tight text-foreground">{title}</h1>{description && <p className="mt-0.5 max-w-4xl text-[12px] leading-5 text-muted-foreground/75">{description}</p>}</div>{actions && <div className="flex w-full flex-wrap items-center gap-2 sm:w-auto sm:shrink-0 sm:justify-end">{actions}</div>}</div></header>; }
export function SectionHeader({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) { return <div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-center"><div><h2 className="text-[14px] font-semibold text-foreground">{title}</h2>{description && <p className="mt-0.5 text-[11px] leading-4 text-muted-foreground/75">{description}</p>}</div>{actions}</div>; }
